### ISSUE TITLE
CoreAudio support for the player on OSX

### ISSUE THREAD

**Issue by psi29a** [Mindwerks/wildmidi#10]
R-Lind wants to support CoreAudio (on OSX) so that we at least can output sound instead of just to a WAV file.

The beginnings of support are there in CMake, but there are still a few things to do.

**Comment by sezero** [comment]
We have coreaudio output for mac since 0.4.6: Is the old (2014) coreaudio branch still relevant? Can we delete it?

**Comment by sezero** [comment]
> We have coreaudio output for mac since 0.4.6: Is the old (2014) coreaudio branch still relevant? Can we delete it?

Deleted the outdated branch. It was from early 0.3.x times, I can backport coreaudio support from 0.4.x to 0.3.x if really really wanted, later on.

**Comment by psi29a** [comment]
> > We have coreaudio output for mac since 0.4.6: Is the old (2014) coreaudio branch still relevant? Can we delete it?
> 
> Deleted the outdated branch. It was from early 0.3.x times, I can backport coreaudio support from 0.4.x to 0.3.x if really really wanted, later on.

No need for me; I think you wanted to maintain 0.3 because it sounds different than 0.4/0.5 right?  For me 0.3 is End of Life.
