### ISSUE TITLE
MUS with pitch bend needed for testing.

### ISSUE THREAD

**Issue by chrisisonwildcode** [Mindwerks/wildmidi#102]
At the moment the pitch bend in the mus format is not supported correctly by mus_wm.c at this point.

A mus file with known pitch bend is needed for testing along with an audio file with how the file is meant to sound like. If you you can provide these please let me know.

**Comment by psi29a** [comment]
Aside from the file size difference, it sounds exactly same. Cheers!

Close it and ship it.

**Comment by chrisisonwildcode** [comment]
Closing this for now
