### ISSUE TITLE
too quiet, need louder volume levels.

### ISSUE THREAD

**Issue by chrisisonwildcode** [Mindwerks/wildmidi#103]
I write this to help think out loud so that others may know my thinking.

I propose a different approach that will dynamically adjust the volume within a very short amount of time (hardly noticeable to our ears) that will result in no need for clamping. The proper term is call "Look ahead brick wall limiter". In WildMIDI the implementation would not be exact due to dealing with small chunks of audio data at a time but this is how I propose it works.

mix everything as per normal in the core of the lib. But instead of at the end going through and clamping the values, call a function that will then do the following:

1) check to see if next peak/trough is outside limits. If so set a variable that says the goal of how much we need to adjust the volume level of that peak/trough, otherwise unset the volume adjust level.

2a) if volume adjust level is set, and is not equal to the goal, adjust the level towards the goal so we reach our goal volume adjust level within 0.002 seconds of being first detected.

2b) if however we don't need to adjust the volume but we are still recovering from a previous volume adjust, alter the volume enough so overall it returns to normal within 0.004 seconds.

3) adjust volume of level (if needed)

4) at the end of processing the sample chunk store in the MDI struct the volume adjust level and goal.

In a nut shell what we will be trying to do is to compress (not clamp) audio signals that go outside of the storage limits. This would result in better quality output.

Downsides:
- either end of the audio chunks being processed might create clicks under certain conditions. Will have to look at a way to limit that possibility.
- slightly longer processing times (especially when some of the task may require conversion to doubles)
- louder than any of our previous releases
- some distortion may occur do to reshaping of the signal, but until I am ready to test I am unsure. This is especially so on the ends of the audio chunk being processed.

I will put together a function to demonstrate this better and throw it into wildmidi-updates.

**Comment by chrisisonwildcode** [comment]
Working on this until someone brings me an issue to poke a stick at ...

**Comment by psi29a** [comment]
We need to start thinking about a release. Is your update-branch ready?  Is this particular issue necessary for 0.4 or can it go into 0.4.1? Is this issue something that was in 0.3.x?

**Comment by chrisisonwildcode** [comment]
I am still concerned about volume levels, if you can let me work out a solution for 0.4 release then I'll have a base to work from further if needed.

**Comment by psi29a** [comment]
OK, sure!  So this is the last one then we can release!? :)  yay

That's great, I'll start looking at open issues to push to 0.4.1

@sezero anything in this branch we want to backport to 0.3 or are going to skip work there and focus exclusively on 0.4? I would prefer that we let 0.3 branch be retired unless you have a compelling reason to keep it alive?

**Comment by sezero** [comment]
On 1/2/15, Bret Curtis <notifications@github.com> wrote:
> @sezero anything in this branch we want to backport to 0.3 or are going to
> skip work there and focus exclusively on 0.4? I would prefer that we let 0.3
> branch be retired unless you have a compelling reason to keep it alive?

I don't see anything in master or wildcode-updates to be backported
to the 0.3 branch yet, but that is limited to how good I followed the
changes: so if there are any bug fixes to be applied to it, please tell
me. Other than that, I suggest that we keep the branch so that we can
apply bug fixes whenever needed.

**Comment by psi29a** [comment]
The 0.3 branch will stay, not deleting or anything. I just didn't plan on any more releases unless someone wants bug-fixes.

**Comment by chrisisonwildcode** [comment]
Seems like an interesting issue is going on .... while trying to work out why I am getting clipping effect when the audio data isn't even reaching levels that would clip I came across something else ...

first value placed into the output buffer by the lib ...
Left: 2468, Right: 5254

first value in the output buffer as seen by the player ...
Buffer -23543 <<>> -31212 

WTF ... can someone do a valgrind run please incase something is getting stomped on that shouldn't

**Comment by psi29a** [comment]
@chrisisonwildcode I can do a bit tomorrow morning, do you have an example file/midi to run against?

**Comment by chrisisonwildcode** [comment]
EVERYONE: Please test wildcode-updates for audible clipping and clicks. You might want to adjust your volume down a little while you are at it.

Report any issues with a link to the midi file please.

**Comment by chrisisonwildcode** [comment]
Just to let everyone know that enhanced resampling was disabled in -updates while this was being worked on. It has now been re-enabled since the volume issue has now been overcome.

**Comment by psi29a** [comment]
Take the 1.FSEQ xmi file I sent you by email and try playing it back... sounds great. Then try enhanced resampling, then it sounds like half of the instruments fall silent.

**Comment by chrisisonwildcode** [comment]
Try now :)

**Comment by chrisisonwildcode** [comment]
Would like some comments on the low volume (fix) to know that it is working ok for you guys plus is at a nice level for you guys.

**Comment by psi29a** [comment]
OK, sounds normal... though I don't hear much of a difference. ;)

**Comment by chrisisonwildcode** [comment]
The difference between normal and enhanced is subtle, I can hear it when I switch between the 2, without out knowing how to describe it properly ... enhanced seems to give the sounds more brightness.

now, play something with trunk, then again with -updates without changing anything and tell me if you notice the volume difference

**Comment by psi29a** [comment]
I do notice the volume, but I'm no audiophile... shitty laptop speakers. ;) I think it is good here.

**Comment by psi29a** [comment]
@chrisisonwildcode can this be closed?

**Comment by chrisisonwildcode** [comment]
I was waiting to hear all your opinions on if it's now "loud" enough ...

**Comment by psi29a** [comment]
Loud enough for me.

**Comment by psi29a** [comment]
@sezero is this also good for you?

**Comment by sezero** [comment]
On 2/8/15, Bret Curtis <notifications@github.com> wrote:
> @sezero is this also good for you?

It sounds fair.
