### ISSUE TITLE
Increase CI coverage by supporting osx and windows

### ISSUE THREAD

**Issue by psi29a** [Mindwerks/wildmidi#105]
We can tell travisci to run our builds also on OSX.

Over at ci.appveyor.com, we can setup windows builds as well!

Example:
https://ci.appveyor.com/project/erwincoumans/bullet3/build/1.0.98

**Comment by chrisisonwildcode** [comment]
Yes please :) for OSX ... I would love to get wildmidi compiling and running again under cygwin but the cmake magic might not have the right mojo ...

**Comment by psi29a** [comment]
cygwin? if you want too... i use plane old msvc or mingw

**Comment by sezero** [comment]
Hijacking this thread to notify you guys that travis is failing for clang builds for some time: I guess their clang installation (lack thereof??) is a problem.

**Comment by psi29a** [comment]
I've been neglecting this for awhile now...  good news is, I've a lot of experience with travis with other projects, so getting this up and running shouldn't be a problem.

Thanks for bringing this back up to my attention.

**Comment by psi29a** [comment]
Time to look into this properly.

**Comment by psi29a** [comment]
Working on this now.

**Comment by psi29a** [comment]
Done: https://travis-ci.org/Mindwerks/wildmidi/builds/149464666

We have Debug and Release builds on Linux and OSX, including Clang (scan-build) that runs as well.
Two major platforms now supported.
