### ISSUE TITLE
-Warray-bounds warnings in wildcode-updates

### ISSUE THREAD

**Issue by sezero** [Mindwerks/wildmidi#111]
Current wildcode-updtaes branch spits seveal warnings.
The github markdown sh.t will f.ck up the text I think, but here goes.

From gcc-4.8:
<code>
In file included from src/wildmidi_lib.c:57:0:
include/gus_pat.h:31:14: warning: ‘env_time_table’ defined but not used [-Wunused-variable]
 static float env_time_table[] = {
              ^
src/hmi.c: In function ‘_WM_ParseNewHmi’:
src/hmi.c:121:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (hmi_size < (370 + (hmi_track_cnt * 17))) {
                  ^
src/internal_midi.c: In function ‘_WM_AdjustNoteVolumes’:
src/internal_midi.c:483:5: warning: comparison is always false due to limited range of data type [-Wtype-limits]
     if (pan_ofs < 0) pan_ofs = 0;
     ^
src/internal_midi.c: In function ‘_WM_do_sysex_roland_reset’:
src/internal_midi.c:465:35: warning: array subscript is above array bounds [-Warray-bounds]
     uint8_t pan_ofs = mdi->channel[ch].balance + mdi->channel[ch].pan - 64;
                                   ^
src/internal_midi.c:465:62: warning: array subscript is above array bounds [-Warray-bounds]
     uint8_t pan_ofs = mdi->channel[ch].balance + mdi->channel[ch].pan - 64;
                                                              ^
src/internal_midi.c:488:45: warning: array subscript is above array bounds [-Warray-bounds]
         premix_dBm = dBm_volume[mdi->channel[ch].volume] +
                                             ^
src/internal_midi.c:489:45: warning: array subscript is above array bounds [-Warray-bounds]
                      dBm_volume[mdi->channel[ch].expression] +
                                             ^
src/internal_midi.c:490:45: warning: array subscript is above array bounds [-Warray-bounds]
                      dBm_volume[mdi->channel[ch].pressure] +
                                             ^
src/internal_midi.c:499:57: warning: array subscript is above array bounds [-Warray-bounds]
         premix_lin = (float)(_WM_lin_volume[mdi->channel[ch].volume] +
                                                         ^
src/internal_midi.c:500:57: warning: array subscript is above array bounds [-Warray-bounds]
                              _WM_lin_volume[mdi->channel[ch].expression] +
                                                         ^
src/internal_midi.c:501:57: warning: array subscript is above array bounds [-Warray-bounds]
                              _WM_lin_volume[mdi->channel[ch].pressure] +
                                                         ^
src/internal_midi.c: In function ‘_WM_do_sysex_yamaha_reset’:
src/internal_midi.c:465:35: warning: array subscript is above array bounds [-Warray-bounds]
     uint8_t pan_ofs = mdi->channel[ch].balance + mdi->channel[ch].pan - 64;
                                   ^
src/internal_midi.c:465:62: warning: array subscript is above array bounds [-Warray-bounds]
     uint8_t pan_ofs = mdi->channel[ch].balance + mdi->channel[ch].pan - 64;
                                                              ^
src/internal_midi.c:488:45: warning: array subscript is above array bounds [-Warray-bounds]
         premix_dBm = dBm_volume[mdi->channel[ch].volume] +
                                             ^
src/internal_midi.c:489:45: warning: array subscript is above array bounds [-Warray-bounds]
                      dBm_volume[mdi->channel[ch].expression] +
                                             ^
src/internal_midi.c:490:45: warning: array subscript is above array bounds [-Warray-bounds]
                      dBm_volume[mdi->channel[ch].pressure] +
                                             ^
src/internal_midi.c:499:57: warning: array subscript is above array bounds [-Warray-bounds]
         premix_lin = (float)(_WM_lin_volume[mdi->channel[ch].volume] +
                                                         ^
src/internal_midi.c:500:57: warning: array subscript is above array bounds [-Warray-bounds]
                              _WM_lin_volume[mdi->channel[ch].expression] +
                                                         ^
src/internal_midi.c:501:57: warning: array subscript is above array bounds [-Warray-bounds]
                              _WM_lin_volume[mdi->channel[ch].pressure] +
                                                         ^
</code>

From gcc-4.9 or gcc-5.0:
<code>
In file included from src/wildmidi_lib.c:57:0:
include/gus_pat.h:31:14: warning: 'env_time_table' defined but not used [-Wunused-variable]
 static float env_time_table[] = {
              ^
src/hmi.c: In function '_WM_ParseNewHmi':
src/hmi.c:121:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (hmi_size < (370 + (hmi_track_cnt * 17))) {
                  ^
src/internal_midi.c: In function '_WM_AdjustNoteVolumes':
src/internal_midi.c:483:17: warning: comparison is always false due to limited range of data type [-Wtype-limits]
     if (pan_ofs < 0) pan_ofs = 0;
                 ^
src/internal_midi.c: In function '_WM_do_sysex_yamaha_reset':
src/internal_midi.c:465:35: warning: array subscript is above array bounds [-Warray-bounds]
     uint8_t pan_ofs = mdi->channel[ch].balance + mdi->channel[ch].pan - 64;
                                   ^
src/internal_midi.c:465:62: warning: array subscript is above array bounds [-Warray-bounds]
     uint8_t pan_ofs = mdi->channel[ch].balance + mdi->channel[ch].pan - 64;
                                                              ^
src/internal_midi.c:488:45: warning: array subscript is above array bounds [-Warray-bounds]
         premix_dBm = dBm_volume[mdi->channel[ch].volume] +
                                             ^
src/internal_midi.c:489:45: warning: array subscript is above array bounds [-Warray-bounds]
                      dBm_volume[mdi->channel[ch].expression] +
                                             ^
src/internal_midi.c:490:45: warning: array subscript is above array bounds [-Warray-bounds]
                      dBm_volume[mdi->channel[ch].pressure] +
                                             ^
src/internal_midi.c:499:57: warning: array subscript is above array bounds [-Warray-bounds]
         premix_lin = (float)(_WM_lin_volume[mdi->channel[ch].volume] +
                                                         ^
src/internal_midi.c:500:57: warning: array subscript is above array bounds [-Warray-bounds]
                              _WM_lin_volume[mdi->channel[ch].expression] +
                                                         ^
src/internal_midi.c:501:57: warning: array subscript is above array bounds [-Warray-bounds]
                              _WM_lin_volume[mdi->channel[ch].pressure] +
                                                         ^
src/internal_midi.c: In function '_WM_do_sysex_roland_reset':
src/internal_midi.c:465:35: warning: array subscript is above array bounds [-Warray-bounds]
     uint8_t pan_ofs = mdi->channel[ch].balance + mdi->channel[ch].pan - 64;
                                   ^
src/internal_midi.c:465:62: warning: array subscript is above array bounds [-Warray-bounds]
     uint8_t pan_ofs = mdi->channel[ch].balance + mdi->channel[ch].pan - 64;
                                                              ^
src/internal_midi.c:488:45: warning: array subscript is above array bounds [-Warray-bounds]
         premix_dBm = dBm_volume[mdi->channel[ch].volume] +
                                             ^
src/internal_midi.c:489:45: warning: array subscript is above array bounds [-Warray-bounds]
                      dBm_volume[mdi->channel[ch].expression] +
                                             ^
src/internal_midi.c:490:45: warning: array subscript is above array bounds [-Warray-bounds]
                      dBm_volume[mdi->channel[ch].pressure] +
                                             ^
src/internal_midi.c:499:57: warning: array subscript is above array bounds [-Warray-bounds]
         premix_lin = (float)(_WM_lin_volume[mdi->channel[ch].volume] +
                                                         ^
src/internal_midi.c:500:57: warning: array subscript is above array bounds [-Warray-bounds]
                              _WM_lin_volume[mdi->channel[ch].expression] +
                                                         ^
src/internal_midi.c:501:57: warning: array subscript is above array bounds [-Warray-bounds]
                              _WM_lin_volume[mdi->channel[ch].pressure] +
                                                         ^
</code>

**Comment by chrisisonwildcode** [comment]
ok, GCC is nuts (sort of) ... env_time_table is used in a couple of different .c's but not in wildmidi_lib.c ... so I guess I'll have to have a conditionally defined entry for env_time_table in gus_pat.h ...

**Comment by chrisisonwildcode** [comment]
-Warray-bounds seems to be giving bogus warnings but I will put some additional if statements in and see if that shuts it up ...

**Comment by chrisisonwildcode** [comment]
Anyone know if Xcode can be made to give this level of warnings?

**Comment by sezero** [comment]
On 1/4/15, chrisisonwildcode <notifications@github.com> wrote:
> Anyone know if Xcode can be made to give this level of warnings?

Recent xcode uses llvm/clang, and I guess your xcode is recent too.
My clang-3.4.2 doesn't report those warnings.

**Comment by chrisisonwildcode** [comment]
ok, gcc is nuts ...

from sezero's post 
^ src/hmi.c: In function ‘_WM_ParseNewHmi’: src/hmi.c:121:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare] if (hmi_size < (370 + (hmi_track_cnt * 17))) {

hmi_size is an uint32_t and  hmi_track_cnt is a uint8_t .... whats with this warning ...

**Comment by chrisisonwildcode** [comment]
sezero: I have fixed the -Wtype-limits warning and the -Wunused-variable warning. Can you please re-run that and tell me if you still get the bounds warnings ... if you do I'll have to put a bunch of if's in there to prevent them ...

**Comment by sezero** [comment]
On 1/4/15, chrisisonwildcode <notifications@github.com> wrote:
> ok, gcc is nuts ...
>
> from sezero's post
> ^ src/hmi.c: In function ‘_WM_ParseNewHmi’: src/hmi.c:121:18: warning:
> comparison between signed and unsigned integer expressions [-Wsign-compare]
> if (hmi_size < (370 + (hmi_track_cnt * 17))) {
>
> hmi_size is an uint32_t and  hmi_track_cnt is a uint8_t .... whats with this
> warning ...

I think hmi_track_cnt is being promoted to and int, thus the warning

**Comment by sezero** [comment]
On 1/4/15, chrisisonwildcode <notifications@github.com> wrote:
> sezero: I have fixed the -Wtype-limits warning and the -Wunused-variable
> warning. Can you please re-run that and tell me if you still get the bounds
> warnings ... if you do I'll have to put a bunch of if's in there to prevent
> them ...

Up-to-date wildcode-updates + gcc4.9:

src/hmi.c: In function '_WM_ParseNewHmi':
src/hmi.c:121:18: warning: comparison between signed and unsigned
integer expressions [-Wsign-compare]
     if (hmi_size < (370 + (hmi_track_cnt * 17))) {
                  ^
src/internal_midi.c: In function '_WM_do_sysex_yamaha_reset':
src/internal_midi.c:465:35: warning: array subscript is above array
bounds [-Warray-bounds]
     uint8_t pan_ofs = mdi->channel[ch].balance + mdi->channel[ch].pan - 64;
                                   ^
src/internal_midi.c:465:62: warning: array subscript is above array
bounds [-Warray-bounds]
     uint8_t pan_ofs = mdi->channel[ch].balance + mdi->channel[ch].pan - 64;
                                                              ^
src/internal_midi.c:487:45: warning: array subscript is above array
bounds [-Warray-bounds]
         premix_dBm = dBm_volume[mdi->channel[ch].volume] +
                                             ^
src/internal_midi.c:488:45: warning: array subscript is above array
bounds [-Warray-bounds]
                      dBm_volume[mdi->channel[ch].expression] +
                                             ^
src/internal_midi.c:489:45: warning: array subscript is above array
bounds [-Warray-bounds]
                      dBm_volume[mdi->channel[ch].pressure] +
                                             ^
src/internal_midi.c:498:57: warning: array subscript is above array
bounds [-Warray-bounds]
         premix_lin = (float)(_WM_lin_volume[mdi->channel[ch].volume] +
                                                         ^
src/internal_midi.c:499:57: warning: array subscript is above array
bounds [-Warray-bounds]
                              _WM_lin_volume[mdi->channel[ch].expression] +
                                                         ^
src/internal_midi.c:500:57: warning: array subscript is above array
bounds [-Warray-bounds]
                              _WM_lin_volume[mdi->channel[ch].pressure] +
                                                         ^
src/internal_midi.c: In function '_WM_do_sysex_roland_reset':
src/internal_midi.c:465:35: warning: array subscript is above array
bounds [-Warray-bounds]
     uint8_t pan_ofs = mdi->channel[ch].balance + mdi->channel[ch].pan - 64;
                                   ^
src/internal_midi.c:465:62: warning: array subscript is above array
bounds [-Warray-bounds]
     uint8_t pan_ofs = mdi->channel[ch].balance + mdi->channel[ch].pan - 64;
                                                              ^
src/internal_midi.c:487:45: warning: array subscript is above array
bounds [-Warray-bounds]
         premix_dBm = dBm_volume[mdi->channel[ch].volume] +
                                             ^
src/internal_midi.c:488:45: warning: array subscript is above array
bounds [-Warray-bounds]
                      dBm_volume[mdi->channel[ch].expression] +
                                             ^
src/internal_midi.c:489:45: warning: array subscript is above array
bounds [-Warray-bounds]
                      dBm_volume[mdi->channel[ch].pressure] +
                                             ^
src/internal_midi.c:498:57: warning: array subscript is above array
bounds [-Warray-bounds]
         premix_lin = (float)(_WM_lin_volume[mdi->channel[ch].volume] +
                                                         ^
src/internal_midi.c:499:57: warning: array subscript is above array
bounds [-Warray-bounds]
                              _WM_lin_volume[mdi->channel[ch].expression] +
                                                         ^
src/internal_midi.c:500:57: warning: array subscript is above array
bounds [-Warray-bounds]
                              _WM_lin_volume[mdi->channel[ch].pressure] +
                                                         ^

**Comment by sezero** [comment]
On 1/4/15, chrisisonwildcode <notifications@github.com> wrote:
> sezero: I have fixed the -Wtype-limits warning and the -Wunused-variable
> warning. Can you please re-run that and tell me if you still get the bounds
> warnings ... if you do I'll have to put a bunch of if's in there to prevent
> them ...

RE: hmi_track_cnt :  changing its tye to uint32_t cures the warning.

**Comment by chrisisonwildcode** [comment]
will do ....

Also can you please update your source and check for -Warray-bounds please. Fingers crossed this works ...

**Comment by sezero** [comment]
On 1/4/15, chrisisonwildcode <notifications@github.com> wrote:
> will do ....
>
> Also can you please update your source and check for -Warray-bounds please.
> Fingers crossed this works ...

Here goes, from gcc4.9 :

src/hmi.c: In function '_WM_ParseNewHmi':
src/hmi.c:121:18: warning: comparison between signed and unsigned
integer expressions [-Wsign-compare]
     if (hmi_size < (370 + (hmi_track_cnt * 17))) {
                  ^
src/internal_midi.c: In function '_WM_do_sysex_yamaha_reset':
src/internal_midi.c:465:35: warning: array subscript is above array
bounds [-Warray-bounds]
     uint8_t pan_ofs = mdi->channel[ch].balance + mdi->channel[ch].pan - 64;
                                   ^
src/internal_midi.c:465:62: warning: array subscript is above array
bounds [-Warray-bounds]
     uint8_t pan_ofs = mdi->channel[ch].balance + mdi->channel[ch].pan - 64;
                                                              ^
src/internal_midi.c:487:45: warning: array subscript is above array
bounds [-Warray-bounds]
         premix_dBm = dBm_volume[mdi->channel[ch].volume] +
                                             ^
src/internal_midi.c:488:45: warning: array subscript is above array
bounds [-Warray-bounds]
                      dBm_volume[mdi->channel[ch].expression] +
                                             ^
src/internal_midi.c:489:45: warning: array subscript is above array
bounds [-Warray-bounds]
                      dBm_volume[mdi->channel[ch].pressure] +
                                             ^
src/internal_midi.c:498:57: warning: array subscript is above array
bounds [-Warray-bounds]
         premix_lin = (float)(_WM_lin_volume[mdi->channel[ch].volume] +
                                                         ^
src/internal_midi.c:499:57: warning: array subscript is above array
bounds [-Warray-bounds]
                              _WM_lin_volume[mdi->channel[ch].expression] +
                                                         ^
src/internal_midi.c:500:57: warning: array subscript is above array
bounds [-Warray-bounds]
                              _WM_lin_volume[mdi->channel[ch].pressure] +
                                                         ^
src/internal_midi.c: In function '_WM_do_sysex_roland_reset':
src/internal_midi.c:465:35: warning: array subscript is above array
bounds [-Warray-bounds]
     uint8_t pan_ofs = mdi->channel[ch].balance + mdi->channel[ch].pan - 64;
                                   ^
src/internal_midi.c:465:62: warning: array subscript is above array
bounds [-Warray-bounds]
     uint8_t pan_ofs = mdi->channel[ch].balance + mdi->channel[ch].pan - 64;
                                                              ^
src/internal_midi.c:487:45: warning: array subscript is above array
bounds [-Warray-bounds]
         premix_dBm = dBm_volume[mdi->channel[ch].volume] +
                                             ^
src/internal_midi.c:488:45: warning: array subscript is above array
bounds [-Warray-bounds]
                      dBm_volume[mdi->channel[ch].expression] +
                                             ^
src/internal_midi.c:489:45: warning: array subscript is above array
bounds [-Warray-bounds]
                      dBm_volume[mdi->channel[ch].pressure] +
                                             ^
src/internal_midi.c:498:57: warning: array subscript is above array
bounds [-Warray-bounds]
         premix_lin = (float)(_WM_lin_volume[mdi->channel[ch].volume] +
                                                         ^
src/internal_midi.c:499:57: warning: array subscript is above array
bounds [-Warray-bounds]
                              _WM_lin_volume[mdi->channel[ch].expression] +
                                                         ^
src/internal_midi.c:500:57: warning: array subscript is above array
bounds [-Warray-bounds]
                              _WM_lin_volume[mdi->channel[ch].pressure] +
                                                         ^

**Comment by chrisisonwildcode** [comment]
grrr, gonna have to have *pointless* boundary checking in those functions I think .... no wonder things become bloatware

**Comment by chrisisonwildcode** [comment]
do me a favour, in internal_midi.c:479 can you please add 

if (ch > 0x0f) ch = 0x0f;

and tell me if the warnings do away please?

**Comment by chrisisonwildcode** [comment]
putting in a fix based on ch being the cause ... it was the only thing common in all those -Warray-bounds warnings

**Comment by sezero** [comment]
On 1/4/15, chrisisonwildcode <notifications@github.com> wrote:
> do me a favour, in internal_midi.c:479 can you please add
>
> if (ch > 0x0f) ch = 0x0f;
>
> and tell me if the warnings do away please?

Yes. And you did that in the repo, so updated wildcode-updates branch
doesn't emit those warnings

**Comment by chrisisonwildcode** [comment]
let me know if I missed anything

**Comment by sezero** [comment]
On 1/4/15, chrisisonwildcode <notifications@github.com> wrote:
> let me know if I missed anything

This patch simplifies things, if you prefer that way. (sent to your email.)

**Comment by psi29a** [comment]
Looks good, tracking this on our polish issue.
