### ISSUE TITLE
Manpages, who wants to update them?

### ISSUE THREAD

**Issue by chrisisonwildcode** [Mindwerks/wildmidi#112]
With some of the changes that have occurred the manpages may need updating before release.

**Comment by chrisisonwildcode** [comment]
I will be starting to update the man page, including modifying existing ones to match syntax/API changes, and adding manages for new API functions.

Also I will be updating the player man page to include supported formats, options, keys, etc ...

If I need to wait before updating the man page for anything then please let me know.

**Comment by psi29a** [comment]
How much work is this? Otherwise we delay to 0.4.1...

**Comment by chrisisonwildcode** [comment]
Not too much work, just making sure that everything is covered for developers.

Chris

**Comment by psi29a** [comment]
@chrisisonwildcode this is probably the last thing that needs to be done for 0.4 then we can release! :D

**Comment by chrisisonwildcode** [comment]
If you can wait a few more days I can get the manpages done.

**Comment by sezero** [comment]
I did a few updates to the man pages in commit 1a94ad3.
Nothing close to being complete, though. Please check it
for correctness, etc.  Things left to do:
- man pages for newly added library functions
- updating the player man page for new changes
- decide the fate of WildMidi_Live(nonexistent) man page
- decide the fate of ProgRef.odt (if wee keep it, it will
  need maintenance.)
- possibly other things..

**Comment by psi29a** [comment]
You can always keep WildMidi_live man page in an apart branch until it does exist. Otherwise we shouldn't advertise it.

**Comment by psi29a** [comment]
btw: https://zz85.github.io/wild-web-midi/

:)

**Comment by psi29a** [comment]
Done
