### ISSUE TITLE
Cmake build system does not include an install target

### ISSUE THREAD

**Issue by pkrcel** [Mindwerks/wildmidi#113]
As the thread title says, the current build system does not (at lest explicitly) support an INSTALL target.

Would you mind adding it for libwildmidi specifically?

**Comment by psi29a** [comment]
in src/CMakeLists.txt, we set our target paths and INSTALL based on those paths.

Do you mean something like this? http://www.cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html#variable:CMAKE_INSTALL_PREFIX

You can specify the prefix yourself with DESTDIR if you don't like the defaults.

**Comment by pkrcel** [comment]
Sorry, I missed that you specifiy there INSTALL targets; anyway if I'm not mistaken (I've checked out master branch) the only INSTALL definitions are enclosed in a if(UNIX AND NOT APPLE) clause.

Of course I'm on Windows using MSYS2 and a X86_64 mingw-w64 toolchain. ^__^

I do specify CMAKE_INSTALL_PREFIX, but based on the resulting makefile no _actual_ install target is defined.

If I do on the prompt:
$> cmake.exe -P cmake_install.cmake 

The only thing that happens is that on the console is shown "Installing Target: Debug".

I'll look into the thing and see if I can add the install target myself.

Cheers
-pkrcel

**Comment by psi29a** [comment]
You're very right, there isn't anything happening on other platforms at the moment, it was enough to see that they compile and I could test them in their build directory.

It should eventually be done, certainly for the 0.4 release (big one).

You're welcome to fork and add them. :)

**Comment by pkrcel** [comment]
Thanks for the prompt response. 

I might try to add the targets myself, I'll let you know if I manage to do anything.

Cheers
-pkrcel

**Comment by psi29a** [comment]
Merged and great work @pkrcel!
