### ISSUE TITLE
player segfaults on error (wildcard on command line)

### ISSUE THREAD

**Issue by chrisisonwildcode** [Mindwerks/wildmidi#117]
ChristophersMBP:Debug chrisisonwildcode$ ./wildmidi -c ~/eawpats/linuxconfig/timidity.cfg ~/Downloads/\*/\*.MID

WildMidi 0.4.0 Open Source Midi Sequencer
Copyright (C) WildMIDI Developers 2001-2014

WildMidi comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it under
the terms and conditions of the GNU General Public License version 3.
For more information see COPYING

Report bugs to https://github.com/Mindwerks/wildmidi/issues
WildMIDI homepage is at http://www.mindwerks.net/projects/wildmidi/

Initializing Sound System
Initializing libWildMidi 0.4.0

 +  Volume up        e  Better resampling    n  Next Midi
 -  Volume down      l  Log volume           q  Quit
 ,  1sec Seek Back   r  Reverb               .  1sec Seek Forward
 m  save as midi     p  Pause On/Off

Playing DESCE000.MID 
n       [Approx  2m 58s Total] [   ] [100] [ 0m 33s Processed] [18%] -  
Playing DESCE001.MID 
n       [Approx  1m 59s Total] [   ] [100] [ 0m  2s Processed] [ 2%] /  
Playing DESCE002.MID 
n       [Approx  3m 48s Total] [   ] [100] [ 0m  3s Processed] [ 1%] \  
Playing DESCE003.MID 
n       [Approx  3m 21s Total] [   ] [100] [ 0m  4s Processed] [ 2%] -  
Playing DESCE004.MID 
n       [Approx  3m 46s Total] [   ] [100] [ 0m 14s Processed] [ 6%] \  
Playing DESCE005.MID 
n       [Approx  3m 35s Total] [   ] [100] [ 0m  1s Processed] [ 0%] -  
Playing DESCE006.MID 
n       [Approx  2m 31s Total] [   ] [100] [ 0m  1s Processed] [ 0%] -  
Playing DESCE007.MID 
n       [Approx  3m 14s Total] [   ] [100] [ 0m  8s Processed] [ 4%] |  
Playing NERIAKA.MID 
libWildMidi(_WM_ParseNewMidi:187): ERROR File corrupt (missing EOT)
                                                                   Segmentation fault: 11

**Comment by sezero** [comment]
Can you send the problem file so we can test & debug too?

**Comment by sezero** [comment]
Downloaded NERIAKA.MID from
http://www.winnow.veeshanvault.org/files/noncomic/EQ%20Music/ and
placed a few other midis to the same place it resides, then tried
doing

valgrind ./wildmidi -c /home/ozzie/opt/hexen2/timidity.cfg ../*.MID

and I can not reproduce any segfaults with neither of master, 0.3 and
wildcode-upd branches. Here's my output from the -upd branch:


Playing ELISE.MID
n       [Approx  2m 35s Total] [   ] [100] [ 0m  1s Processed] [ 1%] |
Playing HEX1.MID
n        [Approx  2m 56s Total] [   ] [100] [ 0m  2s Processed] [ 1%] /
Playing LEVEL2.MID
n       [Approx  4m 50s Total] [   ] [100] [ 0m  2s Processed] [ 0%] |
Playing NERIAKA.MID
libWildMidi(_WM_ParseNewMidi:189): ERROR File corrupt (missing EOT)
Skipping NERIAKA.MID
Shutting down sound output

==6485==
==6485== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 15 from 1)
==6485== malloc/free: in use at exit: 60 bytes in 3 blocks.
==6485== malloc/free: 931 allocs, 928 frees, 12,543,566 bytes allocated.
==6485== For counts of detected errors, rerun with: -v
==6485== searching for pointers to 3 not-freed blocks.
==6485== checked 93,312 bytes.
==6485==
==6485== LEAK SUMMARY:
==6485==    definitely lost: 60 bytes in 3 blocks.
==6485==      possibly lost: 0 bytes in 0 blocks.
==6485==    still reachable: 0 bytes in 0 blocks.
==6485==         suppressed: 0 bytes in 0 blocks.
==6485== Rerun with --leak-check=full to see details of leaked memory.

**Comment by chrisisonwildcode** [comment]
I'll have a proper look while I poking around the player ...

**Comment by sezero** [comment]
Reproduced and just fixed the segfault by commit ee199100
Please test on your end too, and I believe this can be closed.

**Comment by chrisisonwildcode** [comment]
closing
