### ISSUE TITLE
Weird Error when I try to update ...

### ISSUE THREAD

**Issue by chrisisonwildcode** [Mindwerks/wildmidi#119]
Maybe its just my grey hairs but when U try to update I get

svn: E175002: REPORT of '/Mindwerks/wildmidi/!svn/bc/1323': 200 OK (https://github.com)

**Comment by chrisisonwildcode** [comment]
managed to get past that one (without doing anything) but how I get

ChristophersMBP:wildmidi-mindwerks chrisisonwildcode$ svn update
Updating '.':
At revision 1324.
ChristophersMBP:wildmidi-mindwerks chrisisonwildcode$ svn commit -m "Some tidy up and moving of the seg fix" branches/wildcode-updates/src/wildmidi_lib.c branches/wildcode-updates/src/wildmidi.c 
Sending        branches/wildcode-updates/src/wildmidi.c
svn: E160042: Commit failed (details follow):
svn: E160042: File or directory 'wildmidi.c' is out of date; try updating
svn: E160024: resource out of date; try updating
ChristophersMBP:wildmidi-mindwerks chrisisonwildcode$

**Comment by chrisisonwildcode** [comment]
not sure what caused the problem but a fresh checkout fixed it.

**Comment by psi29a** [comment]
Why are you using SVN to begin with and not GIT... or am I missing something? :)

**Comment by chrisisonwildcode** [comment]
Xcode uses svn with GitHub

**Comment by psi29a** [comment]
what?  I use xcode on my hackintosh and use git (from homebrew).
