### ISSUE TITLE
install target for OSX? build a framework for OSX?

### ISSUE THREAD

**Issue by sezero** [Mindwerks/wildmidi#122]
Should we provide an 'install' target for OSX ?

Should we provide an option to build a WildMidi.framework ?

**Comment by chrisisonwildcode** [comment]
having issues with new version of cmake ...

<code>
ChristophersMBP:build chrisisonwildcode$ cmake -G Xcode -D WANT_STATIC:BOOL=ON -D WANT_DEVTEST:BOOL=ON ../
-- Build Type: Debug
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   libwildmidi_dynamic

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/chrisisonwildcode/Projects/wildmidi-mindwerks/build
ChristophersMBP:build chrisisonwildcode$ 
</code>

The files after building should be wildmidi, libwildmidi, wildmidi-devtest, wildmidi-static but only wildmidi is being built ...

<code>
ChristophersMBP:build chrisisonwildcode$ ls wildmidi.app/Contents/MacOS/Debug/
wildmidi
ChristophersMBP:build chrisisonwildcode$
</code>

**Comment by psi29a** [comment]
Just FYI: 
http://www.cmake.org/Wiki/CMake_RPATH_handling

OSX does things a bit differently.

**Comment by chrisisonwildcode** [comment]
from what I can tell, on OSX make is not building everything that WANT_ flags are set for. Again maybe I'm doing something wrong, I will continue to look into this especially since detest is a tool I use a lot and would like smoke to compile it for me so I don't have to make it by hand

**Comment by chrisisonwildcode** [comment]
is it possible to get cmake to setup the stuff for an OS X make install?

**Comment by chrisisonwildcode** [comment]
So at the moment, I use cmake to build the Xcode files and Xcode to build and debug. Sometimes I'll use GDB to debug but its only needed on rare occasions.

Yes you have to navigate into the wildmidi.app to access the binaries and lib but at this point a minor inconvenience.

**Comment by psi29a** [comment]
Fixed the RPATH issue when getting WildMIDI to build on OSX via Travis-CI.

At some point I'll get cmake to use cpack to help make .app packages that people can drag-n-drop and install.

Please test and we can close this issue. :)

**Comment by psi29a** [comment]
@sezero almost there, I plan on getting windows/osx/linux builds together using cpack from cmake.

**Comment by chrisisonwildcode** [comment]
with the .app I still have to traverse them to use the binaries within them. I tend to copy them out into my testing directory. I tend to also do static builds as they are easier to debug with lib with.

**Comment by sezero** [comment]
I had added a standalone macosx makefile to bypass cmake crapola:
it links the library with `-Wl,-install_name,"@executable_path/$(LIB_INSTALLNAME)"`
so the wildmidi player linked to it expects the library in the same directory.
That overcomes @chrisisonwildcode's issue of navigating the app, so good.

The remaining thing is generating a `wildmidi.framework` through cmake,
which can wait: changing the milestone to wishlist.

**Comment by sezero** [comment]
I won't bother myself for this further - `WONTFIX`
