### ISSUE TITLE
Potential SEG with events ...

### ISSUE THREAD

**Issue by chrisisonwildcode** [Mindwerks/wildmidi#123]
While working on something I found a potential for a SEG to occur. I will be fixing this and creating a branch for the fix once done.

Basically the issue is in some places there are checks for event->do_event != NULL ... problem is do_event may never be NULL (oversight in my part when reworking the code). It is just pure luck that this has not been encountered until now.

I will be auditing the code looking for these checks to see if they are really needed where they are (less checks means faster code) since we have not encountered the SEG until now.

**Comment by psi29a** [comment]
Clang should have a fuzz checker by now that we can use as well. We should take advantage of that too in the future:
https://github.com/llvm-mirror/clang/tree/master/tools/clang-format/fuzzer

**Comment by chrisisonwildcode** [comment]
This is fixed in the do_event-tidy-up branch. Please check and merge.

**Comment by sezero** [comment]
On 2/9/15, chrisisonwildcode <notifications@github.com> wrote:
> This is fixed in the do_event-tidy-up branch. Please check and merge.

This is broken: playback is completely silent.

If I revert all changes to *midi_setup_*() procedures in internal_midi.c
then it works. (I did keep the changes to _WM_CheckEventMemoryPool()
and _WM_ResetToStart() )

**Comment by sezero** [comment]
> [...]

Besides, I don't see how the code would have segfault'ed
and how the changes are fixing any such possibility.

**Comment by sezero** [comment]
PING:  What do we do with this?

**Comment by chrisisonwildcode** [comment]
I will look into it tonight

**Comment by chrisisonwildcode** [comment]
fixed in the do_event-tidy-up branch ...

**Comment by chrisisonwildcode** [comment]
Re: topic of thread.

While it seems that the code as is/was didn't seem to be able to produce a set up the surface there were quite a few checks for do_event != NULL to test for the end of the events. However do_event wasn't set to NULL on the very last event. It just so happened that other checks prevented a seg from occurring and was not apparent until I tried to do something that relied on do_event == NULL that it was discovered.

**Comment by sezero** [comment]
Do we merge this now?

**Comment by chrisisonwildcode** [comment]
Test it first, if no issues then merge it please

**Comment by sezero** [comment]
Tested briefly and merged to master, deleted the branch.  If any issues ever show up due to those changes, we'll handle them then.
