### ISSUE TITLE
Possible mem leak in Alsa

### ISSUE THREAD

**Issue by psi29a** [Mindwerks/wildmidi#127]
This might not be our problem, but I'm tracking it anyway in case anyone brings it up.
<pre>
/media/workspace/Wildmidi/wildmidi/src/wildmidi.c:755:5: warning: Potential leak of memory pointed to by 'hw'
    snd_pcm_sw_params_alloca(&sw);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/alsa/pcm.h:837:39: note: expanded from macro 'snd_pcm_sw_params_alloca'
#define snd_pcm_sw_params_alloca(ptr) __snd_alloca(ptr, snd_pcm_sw_params)
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/alsa/global.h:106:57: note: expanded from macro '__snd_alloca'
#define __snd_alloca(ptr,type) do { *ptr = (type##_t *) alloca(type##_sizeof()); memset(*ptr, 0, type##_sizeof()); } while (0)
                                                        ^~~~~~~~~~~~~~~~~~~~~~~
/usr/include/alloca.h:35:23: note: expanded from macro 'alloca'
# define alloca(size)   __builtin_alloca (size)
                        ^~~~~~~~~~~~~~~~
/media/workspace/Wildmidi/wildmidi/src/wildmidi.c:762:19: warning: Potential leak of memory pointed to by 'sw'
    send_output = write_alsa_output;
                  ^~~~~~~~~~~~~~~~~
2 warnings generated.
</pre>

**Comment by sezero** [comment]
On 3/2/15, Bret Curtis <notifications@github.com> wrote:
> This might not be our problem, but I'm tracking it anyway in case anyone
> brings it up.

> /media/workspace/Wildmidi/wildmidi/src/wildmidi.c:755:5: warning: Potential
> leak of memory pointed to by 'hw'
>     snd_pcm_sw_params_alloca(&sw);
>     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /usr/include/alsa/pcm.h:837:39: note: expanded from macro
> 'snd_pcm_sw_params_alloca'
> #define snd_pcm_sw_params_alloca(ptr) __snd_alloca(ptr, snd_pcm_sw_params)
>                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /usr/include/alsa/global.h:106:57: note: expanded from macro '__snd_alloca'
> #define __snd_alloca(ptr,type) do { *ptr = (type##_t *)
> alloca(type##_sizeof()); memset(*ptr, 0, type##_sizeof()); } while (0)
>
> ^~~~~~~~~~~~~~~~~~~~~~~
> /usr/include/alloca.h:35:23: note: expanded from macro 'alloca'
> # define alloca(size)   __builtin_alloca (size)
>                         ^~~~~~~~~~~~~~~~
> /media/workspace/Wildmidi/wildmidi/src/wildmidi.c:762:19: warning: Potential
> leak of memory pointed to by 'sw'
>     send_output = write_alsa_output;
>                   ^~~~~~~~~~~~~~~~~
> 2 warnings generated.

Its alloca(), the ptr is stack allocated and lost upon function return.
I guess clang is being more overzealous than it should be.

**Comment by sezero** [comment]
I think we should close this.
