### ISSUE TITLE
0.4 (master) adding silence to end breaks continuous looping of midis

### ISSUE THREAD

**Issue by sezero** [Mindwerks/wildmidi#128]
0.4 (master branch) is adding some silence to the end of midis; that breaks looping midis continuously. This is very noticeable with doom music converted from mus format (using the -x switch of wildmidi player.)

**Comment by chrisisonwildcode** [comment]
Are you talking about -x conversion or the 'm' conversion ... 

-x conversion for mus needs to go to psi29a

As for 'm' conversion I will check to make sure the  silence we add to allow the last notes to fade properly is not being added to the midi file.

**Comment by sezero** [comment]
On 3/12/15, chrisisonwildcode <notifications@github.com> wrote:
> Are you talking about -x conversion or the 'm' conversion ...
>
> -x conversion for mus needs to go to psi29a
>
> As for 'm' conversion I will check to make sure the  silence we add to allow
> the last notes to fade properly is not being added to the midi file.

You are misreading the issue:

I use -x conversion, yes, but that is NOT the issue. The only
reason I mentioned the -x conversion is that I thought that it
would help you to reproduce what I said.

The ISSUE IS that current wildmidi-master is adding silence
to the end of midis during playback which is pretty much
unacceptable: for example, it breaks looped playback of midis.

OTOH, I never used the -m conversion, but seeing that parsed
midis are added silence at the end, I can only imagine that the
-m converted midis will have silence added to then already and
the playback of the output fie will be worse.

**Comment by psi29a** [comment]
There isn't a -m flag, it is a way to dump the midi in the player during playback.  

I think the extra silence at the end of a midi is a nono, though I think it was to try to fix the problem of the ending sometimes being cutoff to soon. I still think that there should be a better way to handle that.

As an aside, we should really only have one (1) way to convert formats to midi. I'm not even sure _why_ we needed to have two ways, since the original code was LGPL to begin with... why re-write it? With the second versions and the hmi/hmp converters... we lost the ability to do conversion without first starting up wildmidi. My main point here is, I don't want two code-bases to do bug fixes for..

**Comment by sezero** [comment]
This is off-topic for this bug item, but I'll say my part about it:  FWIW, I don't like the 'm' option of dumping midi during playback (but it's just me), and I do like the -x option and the way it works without library any init. If we could write something to convert hmi & co files using -x like we do with mus and xmi, I'd like that.  However, I do like Chris's way of directly playing back mus/xmi/hmi/etc, so that means keeping two code bases..

**Comment by psi29a** [comment]
I'm not sure how I feel about having two different ways of converting the same files in the codebase... it is my gut feeling that one has to go. If we could have some type of code reuse, that would be preferable.

**Comment by chrisisonwildcode** [comment]
I thought I replied further to this, but obviously not.

Re: Silence at end ... is there a fixed amount of looping you need to happen? ... I can add an option on midi load that it is to be looped ... This would not only solve your problem but allow us to keep the bit thats added on the end to allow for final note decays. NOTE: its only added if needed.

Re: -x vs 'm' ... If you can to let me think about it some I may be able to master mind a solution that will allow us to use the existing code the library uses for playback for -x without needing to initialise the library (at least externally).

**Comment by sezero** [comment]
On 3/12/15, chrisisonwildcode <notifications@github.com> wrote:
>
> Re: Silence at end ... is there a fixed amount of looping you need to
> happen? ... I can add an option on midi load that it is to be looped ...
> This would not only solve your problem but allow us to keep the bit thats
> added on the end to allow for final note decays. NOTE: its only added if
> needed.

Re: Silence at the end:
To me, even getting incorrect total time is actually bad..

Re: silence at the end and looping:

Not interested about our reference wildmidi player, but only about
using the library. I don't have a fixed number of loop, I myself usually
loop infinitely. For that, I play until WildMidi_GetOutput() returns 0
to indicate end, then I do WildMidi_FastSeek() to start and continue
calling WildMidi_GetOutput(). This is what I do:
http://sourceforge.net/p/uhexen2/code/HEAD/tree/trunk/engine/h2shared/snd_wildmidi.c
Who knows what others would with the library.

**Comment by chrisisonwildcode** [comment]
Will it help you if I add WM_MO_LOOP which will loop the midi automatically (and avoid the silence added to allow for note decay) ...

**Comment by sezero** [comment]
On 3/12/15, chrisisonwildcode <notifications@github.com> wrote:
> Will it help you if I add WM_MO_LOOP which will loop the midi automatically
> (and avoid the silence added to allow for note decay) ...

Would it help looping case? Yes.  It would be a nice new feature.

However, it wouldn't help with old legit code which wouldn't expect
such behavior like extra silence and would have to change code.

Is there no other better way of avoiding the cut-off and allowing
the note decay, without the crazy amount of extra silence ?

**Comment by sezero** [comment]
On 3/13/15, Ozkan Sezer <sezeroz@gmail.com> wrote:
[...]
> Is there no other better way of avoiding the cut-off and allowing
> the note decay, without the crazy amount of extra silence ?
>

I mean, see this comparison, it is crazy:

0.3.8 to 0.4.0 total times: (as reported by wildmidi player)

hex1.mid  :  2m 56s ->  3m  3s
level2.mid:  4m 51s ->  4m 57s
elise.mid :  2m 35s ->  2m 40s
casa3.mid :  3m  2s ->  3m  9s
kyra1a.mid: 12m 35s -> 12m 41s

**Comment by chrisisonwildcode** [comment]
How are the 0.4.0 times if you use the -s switch?

**Comment by chrisisonwildcode** [comment]
Also if you run those midi files through devtest with the -d1 switch, what is the reported times in comparison. The exception will be kyra1a.mid if it is a type 2 midi file as I need to alter devtest to give overall time for type 2 as well as song time.

Note: devtest does not add any silence.

**Comment by sezero** [comment]
On 3/13/15, chrisisonwildcode <notifications@github.com> wrote:
> How are the 0.4.0 times if you use the -s switch?
>

Same values as the ones run without the -s switch

On 3/13/15, chrisisonwildcode <notifications@github.com> wrote:
> Also if you run those midi files through devtest with the -d1 switch, what
> is the reported times in comparison. The exception will be kyra1a.mid if it
> is a type 2 midi file as I need to alter devtest to give overall time for
> type 2 as well as song time.
>

Reporting the last lines before the 'success' message:

hex1.mid ->
Time 02:49.04277    Meta Event: End Of Track

level2.mid: ->
Time 04:50.61857    Meta Event: End Of Track

elise.mid (an rmid file) ->
Time 03:32.31128    Meta Event: End Of Track

casa3.mid ->
Time 03:2.40000    Meta Event: End Of Track

kyra1a.mid (a type2 file) ->
Time 00:0.49167    Meta Event: End Of Track [the last track]

**Comment by chrisisonwildcode** [comment]
@sezero Please check the GetError branch for WM_MO_LOOP option. This should allow you to loop files without the added time on the end that would normally allow for sound releases to complete cleanly.

If you are happy with it can you merge with master and delete. I will also add a command line switch for the same option after the merge as part of a needed update planned for the player help and controls display. I can then look at the timing differences ...

**Comment by sezero** [comment]
The WM_MO_LOOP work is in WildMidi_GetError branch.  Should we merge all including WildMidi_GetError stuff, or should we merge only the WM_MO_LOOP (and possibly the File_check) parts?

**Comment by chrisisonwildcode** [comment]
Merge all and then remove those branches please.

Then I can start on updating documentation.

**Comment by sezero** [comment]
> Merge all and then remove those branches please.
> Then I can start on updating documentation.

Done as you asked.

I pushed cb7632e so that WM_MO_LOOP is recognized by WildMidi_Init(), please verify.

Tested the loop option very briefly in my uhexen2, looping didn't seem seamless. There was leftover notes from last event at the start after the loop. Maybe should go into another bug item.

Keeping this open. The extra silence stuff still needs revising.

**Comment by sezero** [comment]
The original issue of this bug item, i.e. extra silence, is still not fixed.

**Comment by chrisisonwildcode** [comment]
I've got some free time coming up in the next 2 weeks so I can look into it then.

**Comment by psi29a** [comment]
@chrisisonwildcode how is that 2 weeks coming?

**Comment by chrisisonwildcode** [comment]
I'll have to look at this but I suspect yet another switch ...

**Comment by psi29a** [comment]
Another switch I think is fine for now. :)

**Comment by chrisisonwildcode** [comment]
I have an idea on this. Need to investigate something before I run it past you guys. Won't take much (and no switch needed) if my brain is working

**Comment by psi29a** [comment]
Awesome! Lucius over @ https://github.com/luciusDXL/XL-Engine  is waiting on us. :)

He has already integrated wildmidi into it to play back music for daggerfall, blood, dark forces and more. :D

**Comment by chrisisonwildcode** [comment]
So a very brief look at looping and I have an idea, all be it a crazy one.

The problem szero experienced with looping can basically be explained like this.
1. Song needs to loop
2. When song comes to end then everything needs to be reset to start.
3. Problem arrises when last event before sample is fully released.

With the internal format we have 16 channels for events. What I propose is that only for WM_MO_LOOP that any channels where sounds are releasing at the end of the events that they be moved above the normal 16 channels so their sounds releases can be completed without being effected by resets for restarting the loop.

I am really tired after a busy day so please ask questions if that no sense.

Chris

**Comment by psi29a** [comment]
Proof is in the code. :)

**Comment by chrisisonwildcode** [comment]
I think I know how to fix this issue for good, just have to get into the code but I thought I would pass it by you guys.

I gotta refresh myself with the code but this will be one of the first things I plan on fixing.

There seems to be 2 issues going on here.

1. Left over notes from previous loop still playing at the start of the loop

2. Silence between the loops

So the question is how to resolve both these issues, and the answer is we can't and here's why.

While the note off may have been received the sound is still in decay. Note off does not mean the sound stops there, instead it means you "released the key". If the noteoff is received right at the end of the loop, the sound may still be in decay at the re-start of the loop.

Of course leaving a "gap" at the end of a loop to account for decay is not what we want as it may cause undesired results.

Of course we could kill off all sound at the end of the loop, however some loops may rely on the decay of the sound continuing with the re-start of the loop. This would mean some loops are not sounding as intended.

The only option it to continue processing the decay of sound from the previous loop at the restart of the loop, but all so make sure that all "active" notes have been set to a "note off" state at the end of the loop to prevent weirdness where a note may not have a "note off" event within the loop.

Your thoughts?

**Comment by psi29a** [comment]
Make a branch so we can test. :)

**Comment by chrisisonwildcode** [comment]
someone link me supported file that is meant to be looped please, so I can test.

**Comment by chrisisonwildcode** [comment]
please test wildcode_wildmidi branch ...

**Comment by psi29a** [comment]
@sezero You have one we can test?

**Comment by sezero** [comment]
Did not actually run-test anything, but looking at the change applied
in the wildcode_wildmidi branch it only touches playback and does that
only if WM_MO_LOOP is in effect. That doesn't help with the case where
one wants to retrieve the total time of a song, e.g. see comment:
https://github.com/Mindwerks/wildmidi/issues/128#issuecomment-79010593

As for a midi file to test: this is issue have never ever been limited
to any particular midi file, testing can be done with anything.

**Comment by chrisisonwildcode** [comment]
Um, #128 was originally about silence breaking looping ...

Chris

**Comment by chrisisonwildcode** [comment]
I'm gonna add some code to the bits I did already to ensure any active notes are put into a note off state when the loop restarts.

As for silence at end (different issue) I'll have a look when I get home if it can be improved. Currently the bit added to the end is the expected longest remaining decay of the last note's from the noteoff, or at least should be, so I will check that.

**Comment by sezero** [comment]
>  Um, #128 was originally about silence breaking looping ...

No, not just about breaking looping, but about 'adding silence' and whatever it does as a consequence. One such consequence is breaking loop, which you added WM_MO_LOOP as a band-aid (which I didn't really like), and one other consequence is changing of the actual total times. Copied from above:

```
0.3.8 to 0.4.0 total times: (as reported by wildmidi player)
hex1.mid : 2m 56s -> 3m 3s
level2.mid: 4m 51s -> 4m 57s
elise.mid : 2m 35s -> 2m 40s
casa3.mid : 3m 2s -> 3m 9s
kyra1a.mid: 12m 35s -> 12m 41s
```

**Comment by chrisisonwildcode** [comment]
We can cut the sound at the exact time, but it would be harsh and not nice. How do you propose we allow for final decays.

**Comment by chrisisonwildcode** [comment]
Think of it like this ... Note on is like pressing down on a piano key. Note off is like releasing that key. The sound does not suddenly stop as soon as you release the key, there is a decay in the sound. Another example is hitting a crash cymbal, the sound doesn't stop as soon as the drumstick leaves the cymbal. 

A lot of midi files do not account or allow for the decay of the sound after the last note off, that is the job of the software playing the file. Hence we add enough to allow for complete decay.

What I can do is report the time the file states, and state that time was added to the playback allow for final decay via some bug/faq thing.

**Comment by sezero** [comment]
I don't know how you'd allow for final decays any other way, but with
the current version the added extra time is way too much.

As for the explanations, I understand. But we never had added silence
to deal with this thing until very recently and not before some filed
a complaint for it for his midi file.

Now with the current development version: the library is expecting me
to use that WM_MO_LOOP thing (which was non-existent up until now) in
order to loop properly and otherwise f.ck off, and I do NOT have to do
that: I _CAN_ loop by myself just fine if the library hadn't do extra
stuff that, in my own opinion, shouldn't do, at least not in this way
or not in this extreme.

I am just telling you of the problem. You guys do whatever you want to.

**Comment by chrisisonwildcode** [comment]
Here's another option,

We report only the time the midi states but developers wanting a smooth release have to resampling functions until the data returned is less than they requested.

That sound ok?

**Comment by chrisisonwildcode** [comment]
Sorry, forgot to add, then if you wanted to loop you could do a fast seek back to the start, decay of last notes would still play.

One thing to keep in mind is that 0.3 branch added space at the end too

**Comment by chrisisonwildcode** [comment]
Or another option is to add the amount of time we add for final decay to the info stuff that way anyone wanting looping can account for it ... How's that sound as an option, workable for you?

**Comment by sezero** [comment]
I make any remarks on the possible solutions, but what I need in terms
of a user is clear:  The library should output sanely without the song
taking a hell lot of time finish. A library user needn't have to use a
flag like WM_MO_LOOP _at all_, i.e. that flag must only be a convenience
flag for those who don't want to write their own looping, only serving
the purpose of looping. The midis must not have crazy amount of extra
silence at their ends (see the comparative numbers I listed above.) The
implementation details are not my concern any longer.

I am sending the midis I referenced above to your personal email accounts,
in case you want to test with them.

**Comment by psi29a** [comment]
I weighed in on this at the beginning of the thread. Too much time at the end ruins things. So while it would be the most 'correct' way to handle a midi to let the notes decay until the end, it isn't apparently how the music was intended to be heard.

I'm going to assume that when you reach an EoT (End of Track), that that is the moment to cut all notes... even if decaying.

Using Doom's e1m1 music as an example, you can compare what we produce with what is expected.
http://www.vgmpf.com/Wiki/index.php?title=Doom_(DOS)
In the link above, you have the original MUS files and also the rips that stays true to the original sound. 

We can use that as a basis to tweak/trim the decay to more consistent time.

Is this doable?

**Comment by chrisisonwildcode** [comment]
Ok wildcode_wildmidi updated to show why extra time is needed for release of notes and why killing everything at EOT is bad

**Comment by chrisisonwildcode** [comment]
Test away

**Comment by psi29a** [comment]
To quote:

> FF 2F 00 End of Track
> This event is not optional. It is included so that an exact ending point may be specified for the track, so that an exact length is defined, which is necessary for tracks which are looped or concatenated.
http://www.music.mcgill.ca/~ich/classes/mumt306/StandardMIDIfileformat.html

You're not going to tell me that the standard is wrong and the professor is also wrong?

I'm sorry, but 0.4 isn't going to be released until this is fixed.

**Comment by chrisisonwildcode** [comment]
End of track, sound can't still be in decay at that point.

**Comment by chrisisonwildcode** [comment]
Sorry, meant to say that the sound can still be in release at EOT ... EOT just means no more event for that track. 

So we either break the majority of midi files by giving a harsh end to the file, or allow time for the sound to release properly.

Again I stress most midi files do not allow for the release of the sound at the EOT market.

**Comment by chrisisonwildcode** [comment]
If you play from current wildcode_wildmidi you will get a sense of what I am talking about

**Comment by chrisisonwildcode** [comment]
So how about this:

1. Remove _WM_MO_LOOP
2. Have _WM_INFO_ struct report midi time and final decay time ... 
3. Instruct developers that for clean decays at end they need to take into account the final decay time.

How does that sound?

**Comment by chrisisonwildcode** [comment]
Sorry, still waking up. I meant release not decay

**Comment by chrisisonwildcode** [comment]
I'll code it up when I'm properly awake.

**Comment by sezero** [comment]
> So how about this: 1. Remove _WM_MO_LOOP 2. Have _WM_INFO_ struct
> report midi time and final decay time ... 3. Instruct developers
> that for clean decays at end they need to take into account the
> final decay time. How does that sound?
> 
> Sorry, still waking up. I meant release not decay
>


Sounds fair I guess,

**Comment by chrisisonwildcode** [comment]
decided on a slightly better solution ... downloading some midis to test/break it

**Comment by chrisisonwildcode** [comment]
Ok so here is what I come with.

The reported midi file time should be accurate, if not let me know.

Programmer can test current_samples against approx_total_sample for the end of the midi ticks. At this point you could loop the file.

Programmer must take into account thought that further calls to GetOutput may reveal more data as the final EOT triggers a function that calculates the samples required to finish releasing sounds. GetOutput returns 0 when no more data to be read.

Player may go beyond 100% as it completes the releases.

Please, test test test and give feedback.

**Comment by sezero** [comment]
When I test with the newly added --playfrom switch like:
    ./wildmidi -c timidity.cfg --playfrom=170 hex1.mid
then it seems to behave fairly.  However, I wanted to test with manual
fast-forwarding, and bug #137 hit me.

**Comment by sezero** [comment]
Testing the functionality on my "fix_bug_137" (see bug #137) branch seems to behave.

**Comment by chrisisonwildcode** [comment]
can we close this @sezero ?

**Comment by sezero** [comment]
Yes. Closing.

**Comment by psi29a** [comment]
Great.

**Comment by sezero** [comment]
Merged wildcode_wildmidi into master. Keeping wildcode_wildmidi branch for Chris to work.

**Comment by psi29a** [comment]
I'll look into master over lunch to see if there is anything left.

Thank you @sezero for your patience. :)

Thank you @chrisisonwildcode for helping get this squared away. :)
