### ISSUE TITLE
feature request: timeframe to play only

### ISSUE THREAD

**Issue by jasper-e** [Mindwerks/wildmidi#131]
It would be appreciated if the command line interface for wildmidi could handle requests to play only a part of the file only, for example from xth second to yth second (or the same with ticks)

**Comment by psi29a** [comment]
Interesting request, certainly doable.

**Comment by chrisisonwildcode** [comment]
@jasper-e question is, do you want all the notes that would be normally active at that time to be playing from that time, or would you be ok with only new notes?

**Comment by jasper-e** [comment]
@chrisisonwildcode: For me it is perfect to play only the new notes.
So the request could be more precise: start playing new notes at the start of the timeframe and stop at the end of the timeframe.

**Comment by chrisisonwildcode** [comment]
gah, can't believe I didn't get this one out of the way. This is now on my todo list for next release.

**Comment by psi29a** [comment]
0.4.1 then?

**Comment by chrisisonwildcode** [comment]
@jasper-e something like --song-start=0.4 --song-stop=3.2 ?

**Comment by chrisisonwildcode** [comment]
@jasper-e if you test wildcode_wildmidi branch you can use --playfrom=# and --playto=# exclusively or together

**Comment by psi29a** [comment]
Is this in master? If not, I'll push to 0.4.1

**Comment by chrisisonwildcode** [comment]
Make it 0.4.1. I believe it was for the player as you can do it with current lib functions

**Comment by sezero** [comment]
It is _already_ in master.  Should we close this?
