### ISSUE TITLE
How do you make a GUS patch?

### ISSUE THREAD

**Issue by Oflameo** [Mindwerks/wildmidi#133]
Wildmidi takes a Midi file and a GUS patch in as input, but instructions on how to make a GUS patch are pretty hard to come by. The file format is published http://www.onicos.com/staff/iz/formats/guspat.html, but any kind of existing tooling is hard to come by on GNU/Linux at least. I asked around on [Freepats.org](http://lists.zenvoid.org/pipermail/freepats-zenvoid.org/2016-February/000143.html) and you can see the results for yourself.

**Comment by psi29a** [comment]
There are other sound fonts available: http://zandro.freeunixhost.com/opl3/
for example, in sf2 format.

There is also a tool 'unsf' that will convert it into a gus patch set. https://github.com/psi29a/unsf

I hope that helps.

**Comment by sezero** [comment]
Closing
