### ISSUE TITLE
0.4.0 Wishlist

### ISSUE THREAD

**Issue by chrisisonwildcode** [Mindwerks/wildmidi#136]
please reply with what is needed for a 0.4.0 release. I will update this post and any other bug reports as needed.

**Comment by psi29a** [comment]
erm... just that onr thing we've been asking for awhile now. ;)   silence at end of midi

**Comment by chrisisonwildcode** [comment]
currently testing a possible workable solution

**Comment by psi29a** [comment]
Great, now just man page updates and documentation.

**Comment by psi29a** [comment]
https://github.com/afritz1/OpenTESArena/pull/18
^-- they are in need of 0.4 ASAP...

Any progress on this?

**Comment by psi29a** [comment]
@sezero you ready? :)

**Comment by sezero** [comment]
On 6/12/16, Bret Curtis <notifications@github.com> wrote:
> @sezero you ready? :)
>

What shall I do??  IIRC, we were waiting for Chris to update man pages.

**Comment by chrisisonwildcode** [comment]
Can one of you guys do the manpages. I've got 3 weeks to complete about 16 assessments as well as continue getting an organisation up and running. 

Chris

**Comment by psi29a** [comment]
Sure, I'll do my best.

We might have to quickly re-work the XMI support because of a problem with https://github.com/Mindwerks/wildmidi/issues/138

**Comment by psi29a** [comment]
Time to start the release cycle! :)

@sezero are you still able to create the windows releases like you did for 0.3.x branch?  Those have been great and used by lots of people. XLEngine/DaggerXL and OpenTESArena to name a few.

**Comment by sezero** [comment]
Sure. I can do binaries for win32, win64, osx and dos.

**Comment by psi29a** [comment]
Super, I'll also start pushing downstream to update their packages.

**Comment by psi29a** [comment]
tagged!

@sezero can you see this?
https://github.com/Mindwerks/wildmidi/releases/edit/untagged-9feb98c9543bcdd0cfd5

If so, feel free to upload.

I'll start making a release announcement.

**Comment by sezero** [comment]
There are windows issues: I'll need to replace a malloc()+bzero() with a calloc(). There may or may not  be more issues with MSVC. We may need to re-tag when they are solved.

**Comment by psi29a** [comment]
Sure, that isn't a problem.  Let me know when and I'll re-tag.

**Comment by sezero** [comment]
Pushed the change, should be OK now.

**Comment by psi29a** [comment]
Retagged!

Good news is that when you delete the tag, the release goes back to draft mode.  Add new tag back, re-save draft and it uses the new tag. How convenient. :)

**Comment by sezero** [comment]
Uploaded binaries for win32, win64, macosx and msdos. Please check them to be sure.

**Comment by psi29a** [comment]
\o/  Thank you!
