### ISSUE TITLE
XMI support is broken

### ISSUE THREAD

**Issue by kcat** [Mindwerks/wildmidi#138]
Trying to play the XMI files in Arena results in many instruments seeming to be missing. Playing back a standard MID file works, but XMI playback seems flawed.

After a quick look at [the source](https://github.com/Mindwerks/wildmidi/blob/master/src/f_xmidi.c), I think the main problem is that WIldMIDI is ignoring the ```TIMB``` chunk. According to [this format description](http://www.shikadi.net/moddingwiki/XMI_Format), the chunk has an array of MIDI patch and bank numbers, and a MIDI program change event actually refers to that array to set both the patch and bank at the same time, rather than specifying the MIDI patch number directly. This could be why most instruments seem to be missing, because it's not setting the correct bank and patch.

Another potential issue is with the tempo event. [This page](http://www.vgmpf.com/Wiki/index.php?title=XMI) remarks: "Tempo events contained in the EVNT chunks should be ignored; they are vestigial remnants of the original MIDI file converted into the XMI format and do not correspond to the values used by the converted event stream." However, the XMI loader seems to change the tempo when it comes across it.

And on a more general issue, the loader doesn't seem to do any size checking of the chunk lengths to ensure it's not overrunning the input buffer, and some of the chunk lengths aren't read. XMI is a bastardized format, as it's an IFF container file (which was designed for big-endian systems), while the XMI-related chunks were designed for use on x86. So you end up with chunk sizes specified as big-endian, and the chunk data containing little-endian integers. [Here](https://github.com/Mindwerks/wildmidi/blob/master/src/f_xmidi.c#L89) for example, the ```0x00 0x00 0x00 0x02``` bytes are actually the INFO chunk length (```2``` in 32-bit big-endian, as its a 2-byte chunk), while the chunk itself will typically have ```0x01 0x00``` (```1``` in 16-bit little-endian, for 1 song/form).

If I have time, I can try fixing these issues and submitting a pull request, although I can't guarantee when that'll be or how long it'll take to wrap my head around.

**Comment by sezero** [comment]
Are these issues present in xmi2mid.c (the codepath is used when wildmidi is run with -g command line switch.)  AFAICS, it skips the EVNT chunk which is one.

**Comment by kcat** [comment]
> Are these issues present in xmi2mid.c (the codepath is used when wildmidi is run with -g command line switch.)

I'm not sure if I'm doing it right, but ```wildmidi -g # PERCNTRO.XMI``` (where ```#``` is 0, 1, or 2) doesn't play any better. [The source](https://github.com/Mindwerks/wildmidi/blob/master/src/xmi2mid.c#L195) notes "XMIDIs that contain Timbre changes will not convert properly", which I take to mean it too ignores the ```TIMB``` chunks.

**Comment by kcat** [comment]
An update. It seems the missing instruments aren't the fault of the unhandled ```TIMB``` chunk (I'm not sure what that's used for now, since program/patch and controller changes don't reference it). The freepats patchset just doesn't work well for these songs since it doesn't have most of the instruments they try to use. Modifying freepats.cfg to map the missing instruments to something that sounds similar "fixes" that problem.

But there are still a couple problems. The issue with tempo events is as I thought. Some of the songs are playing too fast, and it plays more correctly by forcing it to skip all tempo events instead of allowing the first one.

Also, some of the notes seem to be staying on too long, as if the note duration time isn't being handled correctly. This /could/ be the fault of the patch set, but I don't know since some songs are better than others for having overly long notes.

**Comment by sezero** [comment]
FWIW, I use an old version of eaw patchset for my tests:
http://sf.net/projects/uhexen2/files/HoT%20-%20Support%20Files/midi-instrument%20patches/timidity_patches.tar.gz/download

As for tempo issues, do they happen when wildmidi is run with the -g switch?
@chrisisonwildcode: you have any insight?

Also, it would be nice if we have access to the same xmi files you are testing.

**Comment by kcat** [comment]
> FWIW, I use an old version of eaw patchset for my tests

Yes, this seems to work better out of the box for these songs. Thanks.

> As for tempo issues, do they happen when wildmidi is run with the -g switch?

The tempo does seem to be correct when I use ```-x out.mid -g 0``` and play the resulting midi file. Although playing the xmi directly with just the -g switch (without -x) sounds the same as without the -g switch. 

For examples, [here's a couple songs](https://drive.google.com/open?id=0B9hou_ophnPLVmtteGM4QUx4aXc) which don't come out right (hope I did that correctly, never really used google drive before).
By default, WildMIDI plays TAVERN.XMI in 17 seconds. With the workaround/fix, it's 29 seconds. The latter is certainly more correct. https://youtu.be/biU8ufIC8Vk?t=2500
For the stuck/overlong notes, EVLINTRO.XMI is probably one of the more apparent ones, although it might be difficult to tell if you're not familiar with the song. This is the best I can come up with to show what it should be like: https://youtu.be/biU8ufIC8Vk?t=124 Though being that it's a different soundfont on different hardware, it's difficult to say where the problem might be...

**Comment by psi29a** [comment]
Please try this out:
http://zandro.freeunixhost.com/opl3/

OPL3 patchset that is CC-BY-SA

**Comment by psi29a** [comment]
This is why I don't like the idea of having TWO ways to decode a file. The original code was license compatible with wildmidi to begin with so I have no idea why it had to be re-written. :/

**Comment by kcat** [comment]
> Please try this out:
> http://zandro.freeunixhost.com/opl3/
>
> OPL3 patchset that is CC-BY-SA

When converting that sf2 to a GUS patchset with unsf, it doesn't seem to suffer from the stuck notes. Though it's difficult to tell if I'm just not noticing it with how different and "flat" the OPL sounds by comparison.

**Comment by psi29a** [comment]
Is the Timber problem still there?
Because apparently there is a difference between how xmi2mid works and the other code converts XMI to MID.

**Comment by kcat** [comment]
The issue of the ```TIMB``` chunk turned out to not be a problem with either converter. The patchset was just missing the specific instruments the songs wanted, which made it sound like there was a problem with the song (and I didn't expect so many instruments to be missing).

The tempo problem exists in f_xmi.c, regardless of the patchset, and is fine when converted with xmi2mid.c.

**Comment by sezero** [comment]
The -x switch runs through xmi2mid.c and it is fine: that means we
have to fix the tempo issue in f_xmidi.c for it and it'll be done.

Chris?

**Comment by psi29a** [comment]
@chrisisonwildcode Ping :)

**Comment by kcat** [comment]
I'm just an outsider here, but I think converting xmi (or anything) to mid is the wrong way to go about it, conceptually. In my dealings with .mid, .xmi, .hmi, and other proprietary midi-like formats, with all their eccentricities and capabilities, I find it's generally best to generate midi events over time during playback, using the original data as a source and interpreting it as it's intended to be interpreted. Different formats store their midi events differently, and may have different behaviors for what would be standard stuff, which can be difficult or impossible to replicate in another format (particularly smf, aka standard midi files, which lack features other formats have implemented their own ways; no joke, I've dealt with files that do per-track looping and note-on-with-duration events that cross the loop boundary).

**Comment by psi29a** [comment]
I think that was the intention of f_xmidi.c, which converts XMI into wildmidi's internal format.

**Comment by psi29a** [comment]
From kcat:
f_xmi.c handles tempo at all. http://www.vgmpf.com/Wiki/index.php?title=XMI#Technical
"Tempo events contained in the EVNT chunks should be ignored; they are vestigial remnants of the original MIDI file converted into the XMI format and do not correspond to the values used by the converted event stream."

**Comment by chrisisonwildcode** [comment]
Having a quick look at it, tempo should only be getting set once within an EVNT block. I will check tomorrow when I am more awake.

As for TIMB chunk we were aware that it had a list of patched, however the events tended to have the right patch change anyway.

Having no sound is a little concerning especially since default instrument for a channel should be piano.

Again I will check in the morning.

Chris Ison

**Comment by chrisisonwildcode** [comment]
I can have a quick look at this tonight. Can someone please confirm that all tempo messages in the EVNT chunks are to be ignored. At the moment f_xmidi.c uses the first one in the chunk and ignores the rest.

Chris

**Comment by psi29a** [comment]
@chrisisonwildcode they are all ignored in xmi2midi and it says so in the documentation I provided above.

**Comment by chrisisonwildcode** [comment]
Ok, when I get to my computer tonight I will fix that up.

Chris

**Comment by chrisisonwildcode** [comment]
Sorry for the slight delay, was too tired to think by the time I got home.

Please test master, it now ignores all tempo events within an EVNT chunk.

**Comment by kcat** [comment]
That works, thanks. :) Now there's just a minor compile warning:
```
src/f_xmidi.c:63:13: warning: variable ‘xmi_tempo_set’ set but not used [-Wunused-but-set-variable]
     uint8_t xmi_tempo_set = 0;
             ^
```

**Comment by psi29a** [comment]
Kill it! :D

I'll see about getting man pages updated and we can ship this mother!

**Comment by chrisisonwildcode** [comment]
Thanks sezero :) And thanks Bret :)

**Comment by sezero** [comment]
I guess this can be closed.  If there are still issues, or there are related issues, create a a new bug entry with a reference to this one.
