### ISSUE TITLE
wildmidi fails to load any of Warcraft 1 midi

### ISSUE THREAD

**Issue by loki666** [Mindwerks/wildmidi#157]
files are here http://www.midishrine.com/index.php?id=131

**Comment by psi29a** [comment]
Playing TITLE.MID  Skipping: Error (_WM_ParseNewMidi:187) (missing EOT) (File corrupt)

Apparently the files don't follow the MIDI spec.

**Comment by loki666** [comment]
Yes indeed, still the files works great with others MIDI player.

**Comment by psi29a** [comment]
The fact remains they are still corrupt/misinformed MIDI files and WildMIDI is strict.

**Comment by loki666** [comment]
ok.

**Comment by chrisisonwildcode** [comment]
Just want to point out the the current development of wildmidi has relaxed the EOT rules a little and these now play.
