### ISSUE TITLE
Feature: Find wildmidi.cfg in other paths on Windows

### ISSUE THREAD

**Issue by darkstar** [Mindwerks/wildmidi#159]
On Windows, I want to use wildmidi from the command line from different directories, so I put it in a directory that is in my PATH. However, wildmidi seems to look for its config file always in the current directory so that I have to use -c every time.

I suggest having at least 2 fallback directories to search if no wildmidi.cfg is found in the current directory: %APPDATA%\wildmidi.cfg and the path of the wildmidi.exe file, in that order

**Comment by sezero** [comment]
I don't think that something like this will be implemented in foreseeable future. You can always use the `-c` switch of wildmidi player though.  Closing this.
