### ISSUE TITLE
Devtest reporting longer tracks than player.

### ISSUE THREAD

**Issue by chrisisonwildcode** [Mindwerks/wildmidi#160]
While debugging I noticed devtest is reporting longer tracks than the player. Suspect some timing changes or tempo changes are not being processed by devtest.

Note: devtest does not share code with player/library due to devtest being a platform to debug and understand file formats before they are added to the library.

**Comment by chrisisonwildcode** [comment]
First thing I am going to do is switch devtest to use the format files we use internally. This will make devtest a little cleaner and save on code duplication. I believe this will be a better option. Know for devtest the current format files may have a #ifdef added to them for devtest specific functionality. This is currently undecided as it may not be needed, but just giving a heads up.

Second thing I'm going to do is let you all know that this and other issues are being worked on. For me this is a higher priority that other issues because the informtion devtest puts out helps to locate and identify format issues, which many of the current bugs point to.

Lastly I have just had an operation 4 days ago and still requiring strong pain killers. Do not expect this to be done within the next couple of weeks as it will depend on how long I can tolerate the pain for while sitting up to code. But I am looking into it.

**Comment by psi29a** [comment]
I wish you the best in your recovery! :)

**Comment by sezero** [comment]
Hope you get well soon.

**Comment by chrisisonwildcode** [comment]
As far as tempo stuff goes it shouldn't be an issue now as it was only devtest that had tempo issues. Closing this as my reason for creating it is now fixed.
