### ISSUE TITLE
warnings from newer cmake

### ISSUE THREAD

**Issue by sezero** [Mindwerks/wildmidi#167]
I get this from cmake-3.7.2 (windows, upon hitting 'generate') :

```
Build Type: Release
Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
Will not provide a pkg-config file.
Configuring done
CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.
  Run "cmake --help-policy CMP0043" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.
  Run "cmake --help-policy CMP0043" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

Generating done
```

Will need a solution.

**Comment by psi29a** [comment]
That's weird. So we need to provide our own pkgconfig file?

**Comment by sezero** [comment]
Well, it is perfectly normal to not have pkg-config installed on windows.
We should either restrict it to Linux (Unix?), or not check any pkg-config
installation to provide a *.pc file.

**Comment by sezero** [comment]
Fixed by commit 3746676b

**Comment by sezero** [comment]
> Well, it is perfectly normal to not have pkg-config installed on windows.
> We should either restrict it to Linux (Unix?), or not check any pkg-config
> installation to provide a *.pc file.

To clarify:  We already are providing our pkg-config file (*.pc), but we are
doing that only if pkg-config software is installed which, IMO, isn't nice.

**Comment by psi29a** [comment]
Much nicer, thanks for catching this. We should have seen this on our appveyor build process. :/
