### ISSUE TITLE
pow() vs powf()

### ISSUE THREAD

**Issue by sezero** [Mindwerks/wildmidi#168]
In internal_midi.c:_WM_AdjustNoteVolumes() we use powf() and floats instead
of plain old pow(). Is there a specific reason? Is the extra precision harmful?

**Comment by psi29a** [comment]
is the value being used by the powf just a plain old integer?

**Comment by sezero** [comment]
> Do we gain anything from using pow?

pow() is ansi, powf() is c99. My question remains, i.e.
what do we gain anything from using powf()?

> Is it more CPU intensive than powf?

For x86, it shouldn't be.

**Comment by psi29a** [comment]
You mean standard C or ANSI C?

By default, Microsoft's Visual Studio C Compiler doesn't follow the ANSI C standard.

**Comment by sezero** [comment]
I meant C89, i.e. available practically in every and all libc

**Comment by psi29a** [comment]
As you mentioned for x86 that there shouldn't be, how about our armhf friends (nintendo3dsdevkit and raspberry pi) ?

**Comment by sezero** [comment]
Not just arm, but ppc and any others. (Hope that anyone's listening.)
And we'd like to hear what @chrisisonwildcode has to say (his code and
that's the reason I assigned this to him.)

**Comment by chrisisonwildcode** [comment]
I will have a look

**Comment by sezero** [comment]
> I will have a look

Had any chance to look?

**Comment by chrisisonwildcode** [comment]
Oops, sorry guys.

I've got to finish a research assessment *low grumbling about large word counts* and I will look at this when I get back from town today.

Chris

**Comment by sezero** [comment]
PING ?

**Comment by psi29a** [comment]
@chrisisonwildcode any ideas on this?

**Comment by sezero** [comment]
I guess this question will go unanswered for quite a long time...

**Comment by chrisisonwildcode** [comment]
I have an idea what is going on. 0.4 reworked a lot of the code. There is a flaw in tracking timing changes in the initial read of the midi file. A simular flaw occurs also in devtest.c

**Comment by psi29a** [comment]
Hmmm.. :)

**Comment by sezero** [comment]
> I have an idea what is going on. 0.4 reworked a lot of the code. There is a flaw
> in tracking timing changes in the initial read of the midi file. A simular flaw
> occurs also in devtest.c

I believe your comment was intended for bug #176, yes?

**Comment by psi29a** [comment]
Something interesting, using pow(x, 3) is more cpu intensive than just x * x * x, apparently even modern gcc and clang behave the same.

https://baptiste-wicht.com/posts/2017/09/cpp11-performance-tip-when-to-use-std-pow.html

**Comment by chrisisonwildcode** [comment]
hmmm, I can't see why we couldn't use pow() in there. … can we get -ffast-math happening?
