### ISSUE TITLE
install the pkg-config file (wildmidi.pc) unconditionally?

### ISSUE THREAD

**Issue by sezero** [Mindwerks/wildmidi#169]
I suggest that we unconditionally install our wildmdi.pc pkg-config file.
(discussion initially was at issue #167)

I.e., we can remove the PkgConfig software installation check from
https://github.com/Mindwerks/wildmidi/blob/master/CMakeLists.txt#L252

.. and remove the PKG_CONFIG_FOUND conditions from INSTALL directives from
https://github.com/Mindwerks/wildmidi/blob/master/src/CMakeLists.txt#L274
https://github.com/Mindwerks/wildmidi/blob/master/src/CMakeLists.txt#L311

Thoughts?

**Comment by psi29a** [comment]
I would like to eventually use cpack or something to make an installable release instead of a zip. Keeping this in mind, any unnecessary files for windows shouldn't, imo, be included.

**Comment by sezero** [comment]
We can add a conditional for msvc.. Mingw however might install/use pkg-config and *.pc files.

**Comment by psi29a** [comment]
Not sure a msvc conditional is relevant as packaging is outside the scope of either msvc and mingw. 

Unconditional release of the file would certainly remove this headache.

**Comment by sezero** [comment]
OK then, applied 48ccab5 and closing.
