### ISSUE TITLE
Make WildMIDI available on Homebrew

### ISSUE THREAD

**Issue by Thunderforge** [Mindwerks/wildmidi#172]
It would be great if WildMIDI were available on [Homebrew](https://brew.sh) on macOS. I see that we are already using Homebrew for our [CI Mac scripts](https://github.com/Mindwerks/wildmidi/blob/master/CI/before_install.osx.sh), so it would be good if other projects could install the whole thing in the same way.

**Comment by chrisisonwildcode** [comment]
Um, I just create a project file and load/compile/debug in Xcode.

No homebrew skills

**Comment by Thunderforge** [comment]
[These look like the instructions](http://docs.brew.sh/Formula-Cookbook.html) for adding a library to Homebrew. It looks like the most difficult part is just making sure you have all the dependencies declared in your file, since it compiles it from source.

**Comment by luzpaz** [comment]
Per repology, WildMIDI is available on Homebrew

[![Homebrew package](https://repology.org/badge/version-for-repo/homebrew/wildmidi.svg)](https://repology.org/project/wildmidi/versions)

This ticket can be closed.

**Comment by sezero** [comment]
OK, closing.

**Comment by Thunderforge** [comment]
I successfully installed via Homebrew. Thank you!
