### ISSUE TITLE
Getting ready for 0.4.2

### ISSUE THREAD

**Issue by psi29a** [Mindwerks/wildmidi#174]
@sezero how do you feel about a 0.4.2 release? Do we have enough material?
Are there any lingering issues?

@chrisisonwildcode how about you? Any thoughts?

Here are things we tagged for 0.4.2 but not yet closed:
https://github.com/Mindwerks/wildmidi/milestone/6

**Comment by sezero** [comment]
> @sezero how do you feel about a 0.4.2 release?

No objections from me. 

> Do we have enough material?

We don't have much, but fix for bug #132 can be considered a good motive for a release?

**Comment by sezero** [comment]
As far as I can see, the master branch is in fair shape.
Things in the way of a new release:
- issue #176: Although it is not a regression within the 0.4.x series,
 it _is_ a regression against 0.3.x.
- _maybe_ issue #182???

**Comment by sezero** [comment]
It doesn't seem like we'll have any progress with bug #176 and #182.
Should we release 0.4.2 as is?

**Comment by sezero** [comment]
Released 0.4.2 and closed the 0.4.2 milestone. Closing this one.
Rest of the open issues have either 0.4.3 or wishlist milestone.

**Comment by psi29a** [comment]
Moving on...

**Comment by sezero** [comment]
Debian is still at 0.4.0..

**Comment by psi29a** [comment]
Yeah... waiting for uploaders. :(
