### ISSUE TITLE
remove 'large file support'?

### ISSUE THREAD

**Issue by sezero** [Mindwerks/wildmidi#179]
We add 'large file support' in our cmake file, but we don't need it:
are there any midi files or gus patches that are larger than 2GB?

Should I apply the following?
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 77e5e40..b4725f3 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -55,16 +55,6 @@ IF ((NOT BUILD_SHARED_LIBS) AND (NOT WANT_STATIC))
 ENDIF ()
 
 
-# Platform specific defines
-IF (UNIX)
-    # allow 'large' files in 32 bit builds
-    ADD_DEFINITIONS(
-            -D_LARGEFILE_SOURCE
-            -D_FILE_OFFSET_BITS=64
-            -D_LARGE_FILES
-    )
-ENDIF (UNIX)
-
 IF (OPENBSD)  # Set RPATH for OpenBSD so WildMIDI can find libWildMidi.so
     # use, i.e. don't skip the full RPATH for the build tree
     SET(CMAKE_SKIP_BUILD_RPATH FALSE)
```

**Comment by psi29a** [comment]
If we remove it, Debian complains. I added it to fix their complaining.

What are the benefits of removing it? Is it hurting anything?

**Comment by sezero** [comment]
> If we remove it, Debian complains.

Huh. Stupid complaint IMO, but OK.

> What are the benefits of removing it? Is it hurting anything?

Nothing serious.

Closing this one, then.
