### ISSUE TITLE
No "make install" rule generated for CMAKE_SYSTEM_NAME=Generic

### ISSUE THREAD

**Issue by Ghabry** [Mindwerks/wildmidi#182]
Hi I want to provide a fix for Generic because this currently gets no install rule because "UNIX" is not defined for Generic (so no match in src/CMakeFiles).

But Generic does not support shared libraries, so how shall I handle BUILD_SHARED_LIBS and WANT_STATIC?

Shall I just automatically turn Shared OFF and Static ON for Generic or shall I show an error like "Platform does not support dynamic libraries. Use -DBUILD_SHARED_LIBS=OFF -DWANT_STATIC=ON" ?

**Comment by psi29a** [comment]
Do you mean something like this?
https://github.com/Kitware/CMake/blob/master/Modules/Platform/Generic.cmake

**Comment by Ghabry** [comment]
Yeah I meant Platform/Generic which is the file you linked. I use this to build for some embedded platforms but in case of Wildmidi "make install" rules are not created.

**Comment by psi29a** [comment]
If you want to create a PR, we'd review it and likely merge it in. :)

Otherwise, wait a few and I'll do something in the coming week.

**Comment by Ghabry** [comment]
> What kind of embedded environments are you working with? I'm just curious...

Well, mostly out of lazyness I use "Generic" when cross compiling. Months ago I created PRs for Wii and 3DS support, these are 2 of my target platforms but also Android (CMake has a system type for this but Generic works good enough) and emscripten (web browser). Wildmidi runs flawless everywhere.

Will create a PR :)

**Comment by sezero** [comment]
I think this should be on the wishlist, instead of being in a 0.4.x milestone. Changing so.

**Comment by Ghabry** [comment]
This is solved by now. I just updated all the libraries for the cross-compiling of our engine (easyrpg player) and this worked fine without any patching.
