### ISSUE TITLE
Final Tear 3: insanity.mid (_WM_ParseNewMidi:187) (missing EOT) (File corrupt)

### ISSUE THREAD

**Issue by Ghabry** [Mindwerks/wildmidi#183]
Final Tear 3 is a RPG Maker 2003 game.

Here is the file:
[insanity.zip](https://github.com/Mindwerks/wildmidi/files/1536505/insanity.zip)

Fails with "(_WM_ParseNewMidi:187) (missing EOT) (File corrupt)"

I tested playing the file with Timidity and FmMidi: Plays fine in both.
Can't comment further, no idea how the Midi format works, sorry.

**Comment by psi29a** [comment]
Sounds (pun intended) like the file is missing the End of Track record, as WM correctly detects this. The file should be fixed.

**Comment by Ghabry** [comment]
Okay, so as the name says the file is a bit insane (hihi).

Because the standard indeed says this (just checked it based on your information) I agree that this behaviour is fine.

Maybe tolerating this should be reconsidered when many files are corrupted in such a way but by now this is the first one I ever encountered, so not a big deal.

**Comment by sezero** [comment]
libtimidity doesn't have any problems with this file.

Maybe the strictness of wildmidi can be relaxed a little
when the midi has only one track like this one?

**Comment by chrisisonwildcode** [comment]
I agree, when only one track.

**Comment by psi29a** [comment]
No need to close just yet. :)

**Comment by Ghabry** [comment]
Got another MIDI reported that fails to play because of corrupted EOT:

[Lands_25.zip](https://github.com/Mindwerks/wildmidi/files/1873807/Lands_25.zip)

Appears to be a common problem. Broken MIDI editors everywhere.
