### ISSUE TITLE
Slurred/echoy playback at quick tempos on looped instruments

### ISSUE THREAD

**Issue by CCInc** [Mindwerks/wildmidi#185]
At quick tempos, when a midi file is played back on a slurred instrument (in this example, string ensemble from freepats), the output is "slurred", with the notes not releasing quite when they should.

To reproduce, play back the attached midi files using any config that supports looped patches for the string ensemble. 

I suspect that this is due to looped samples being played all the way through before being cut off, rather than jumping immediately to the release/decay section of the sample.

If somebody more familiar than me with the codebase had any idea on how to fix this before I jump into learning the code, please let me know.

[midi.zip](https://github.com/Mindwerks/wildmidi/files/1671523/midi.zip)

**Comment by chrisisonwildcode** [comment]
On my radar for this weekend
