### ISSUE TITLE
luf2dragon.mid: Sounds different compared to timidity (instrument not turned off?)

### ISSUE THREAD

**Issue by Ghabry** [Mindwerks/wildmidi#186]
I attached the MIDI file and two OGG recordings made with timidity and wildmidi.

Pats file used are at the ones at the bottom of
http://freepats.zenvoid.org/SoundSets/general-midi.html#FreePatsGM

[midi.zip](https://github.com/Mindwerks/wildmidi/files/1754395/midi.zip)

Around 10 seconds in the recording there is a loud "Bell" sound and shortly after in the wildmidi version you constantly here a deep grumbling which isn't in the timidity version. (sorry for the bad explanation, not an audio person ;))

Under Windows the MIDI sounds like timidity.

**Comment by sezero** [comment]
Seems to happen with eawpatches or midia patches too, so not limited to freepats.
Happens in wildmidi-0.3 too, so not limited to wildmidi-0.4.

**Comment by chrisisonwildcode** [comment]
On my radar for this weekend, but after I sus out #185.
