### ISSUE TITLE
Getting ready for 0.4.3, outstanding issues

### ISSUE THREAD

**Issue by sezero** [Mindwerks/wildmidi#201]
I think we have more than enough material for a new 0.4.3 release.

There are still issues that need solving.  E.g.:

- Wrong, very long duration detected for MIDI_0088.MID from Daggerfall
  https://github.com/Mindwerks/wildmidi/issues/176

- impossibly long duration with crafted midi files:
  https://github.com/Mindwerks/wildmidi/issues/200 (might be related to https://github.com/Mindwerks/wildmidi/issues/176)

- more size checks needed in f_hmi.c, f_hmp.c, and possibly f_xmidi.c
  https://github.com/Mindwerks/wildmidi/issues/189

And _maybe_ this one (not really sure):

- song has some breaks
  https://github.com/Mindwerks/wildmidi/issues/158

We can still make a 0.4.3 release and change milestone for the above
to 0.4.4.  What do you think?

**Comment by sezero** [comment]
PING?

**Comment by psi29a** [comment]
PONG... I would hold off on a release of 0.4.3 until we at least fix #200 which may or may not be related to #176

**Comment by sezero** [comment]
> hold off on a release of 0.4.3 until we at least fix #200 which may or may not be related to #176

PING?

**Comment by psi29a** [comment]
@chrisisonwildcode PING

**Comment by sezero** [comment]
I don't think we'll get any 'PONG's soon.

I suggest that we release what we have and leave other stuff in limbo.

**Comment by psi29a** [comment]
OK, I'll give it until this weekend at the very latest.

**Comment by sezero** [comment]
I made a draft-release for 0.4.3.  If updates happen, I can happily refresh.

**Comment by psi29a** [comment]
Great, thanks. :)

**Comment by sezero** [comment]
I think it is 'weekend enough' so I published the 0.4.3 release.

**Comment by psi29a** [comment]
Cheers! :)

I'll see that it gets to Debian -> Ubuntu

**Comment by sezero** [comment]
> I'll see that it gets to Debian -> Ubuntu

Still not there?

**Comment by psi29a** [comment]
Newp... i put out the email the interested party (bugged me for not fixing a bug). If they won't answer by tomorrow, I'll email someone else tomorrow who will likely respond in the next day.
