### ISSUE TITLE
travis failures due to missing libm symbols

### ISSUE THREAD

**Issue by sezero** [Mindwerks/wildmidi#205]
See, e.g.: https://travis-ci.org/Mindwerks/wildmidi/builds/448802284?utm_source=github_status&utm_medium=notification
I first hoped that https://github.com/Mindwerks/wildmidi/commit/1cae6ab16f32c867236e908d43923990fc37a4a7 would fix it, but it obviously does not.

Ideas?

```
[100%] Linking C executable ../wildmidi
/home/travis/build/Mindwerks/wildmidi/build/libWildMidi.so: undefined reference to `sinh'
/home/travis/build/Mindwerks/wildmidi/build/libWildMidi.so: undefined reference to `sin'
/home/travis/build/Mindwerks/wildmidi/build/libWildMidi.so: undefined reference to `cos'
/home/travis/build/Mindwerks/wildmidi/build/libWildMidi.so: undefined reference to `pow'
/home/travis/build/Mindwerks/wildmidi/build/libWildMidi.so: undefined reference to `sqrt'
collect2: error: ld returned 1 exit status
make[2]: *** [wildmidi] Error 1
make[1]: *** [src/CMakeFiles/wildmidi.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by psi29a** [comment]
OK, that's weird.  Is this a one-off or is it now every time we run?

**Comment by psi29a** [comment]
Shouldn't we add to the shared lib not not just to wildmidi player? (or am I reading this wrong)

**Comment by psi29a** [comment]
But... I see that we're already doing that here:
https://github.com/Mindwerks/wildmidi/blob/1cae6ab16f32c867236e908d43923990fc37a4a7/src/CMakeLists.txt#L104

**Comment by sezero** [comment]
Yes: The weird part is the shared lib links, but the exe does not.

**Comment by sezero** [comment]
Can we see the exact command line when the exe is linked on the travis host?

**Comment by sezero** [comment]
Found the bugger.  Fixed as of commit 12ab79b.  Dropped a note to PR #202 for it.

**Comment by psi29a** [comment]
Nice find, that flew under the radar.

**Comment by sezero** [comment]
Yeah.  Our local builds used to work possibly because the libm symbols were satisfied by alsa_lib.
