### ISSUE TITLE
Errors in function _WM_init_reverb in file reverb.c

### ISSUE THREAD

**Issue by M-HT** [Mindwerks/wildmidi#210]
I don't know what the reverb engine is actually doing, but AFAICT all uses of variable `i` in lines [186](https://github.com/Mindwerks/wildmidi/blob/4c501a7d895fe6b9dd6266e01eecab96ac0079bb/src/reverb.c#L186)-[221](https://github.com/Mindwerks/wildmidi/blob/4c501a7d895fe6b9dd6266e01eecab96ac0079bb/src/reverb.c#L221) should be changed to variable `j`, otherwise there are uninitialized values and other unpleasant side-effects.

**Comment by sezero** [comment]
You, sir, seem correct.  Should be fixed now.

wildmidi-0.3 branch:
https://github.com/Mindwerks/wildmidi/commit/305131176096faa836e4b344c53c5f96ad2d92c7

master (0.4.x):
https://github.com/Mindwerks/wildmidi/commit/d2763e608c6b170d1d6e20505d0d991ed83c0b00
