### ISSUE TITLE
wildmidi doesn't warn on missing instruments

### ISSUE THREAD

**Issue by rofl0r** [Mindwerks/wildmidi#221]
after converting the opl3 soundfont in the other mindwerks repo to GUS patch format with unsf, and playing the test.mid file as attached in issue 207, the first few seconds nothing can be heard at all whereas timidity warns about a missing instrument on the same file (using the soundfont with timidity):

```
Playing ../../test.mid
MIDI file: ../../test.mid
Format: 1  Tracks: 7  Divisions: 120
Track name: Rythm Guitar 1
Track name: Rythm Guitar 2
Track name: Bass
Track name: Drums
Track name: SFX (Jet)
Track name: SFX (Rev.)
Drum set 8 is undefined
Tone bank 7 is undefined
No instrument mapped to drum set 0, program 31 - this instrument will not be heard
```

**Comment by sezero** [comment]
Timidity does warn because it's a single executable, whereas wildmidi
uses libWildMidi and we avoid unnecessary prints from the library.

I don't know whether this is worth fixing.

**Comment by rofl0r** [comment]
> we avoid unnecessary prints from the library

that's laudable. is there a way though to make the library report this to the user - the wildmidi frontend in this case?

**Comment by sezero** [comment]
>  is there a way though to make the library report this to the user - the wildmidi frontend in this case?

As of yet, no.

**Comment by sezero** [comment]
This looks like a `WONTFIX`

**Comment by rofl0r** [comment]
there's no plan to add an error code to the api when an instrument is missing ? :eyes:

**Comment by sezero** [comment]
I, for one, don't have any such plans. Current development is more like maintenance anyways.
