### ISSUE TITLE
Getting ready for 0.4.4, outstanding issues

### ISSUE THREAD

**Issue by sezero** [Mindwerks/wildmidi#222]
I think we should make a new 0.4.4 (and a 0.3.16) maintenance release.

Long-standing issues that need solving. E.g.:

- Certain MIDIs loop too soon (from Rise of the Triad) in 0.4.3 (#213)
- Wrong, very long duration detected for MIDI_0088.MID from Daggerfall (#176)
- more size checks needed in f_hmi.c, f_hmp.c, and possibly f_xmidi.c (#189)

And maybe this one (not really sure):
- song has some breaks (#158)

I don't know how fixable they are in a short time (unless @chrisisonwildcode
takes action), so I think that we can still make a v0.4.4 release and change
milestone for the above to 0.4.5. What do you think?

**Comment by sezero** [comment]
BTW, these are the list of changes since previous release:

- Fixed integer overflow in midi parser sample count calculation
 (bug #200).
- Fixed 8 bit ping pong GUS patch loaders (bug #207).
- Fixed wrong variable use in reverb code (bug #210).
- Reset block status of tty after playback (bug #211).
- Fixed broken file name handling for 'save as midi' command during
  playback.
- CMake project improvements (bugs: #214, #216, #217, #218) - cmake
  version 3.1 or newer is now required.

**Comment by mcejp** [comment]
Re #214: could we also have something like

`target_include_directories(libwildmidi_static INTERFACE $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>)`

so that projects pulling in Wildmidi via `add_subdirectory` + `target_link_libraries` get the include path wired up auto-magically? (I could work on this)

**Comment by sezero** [comment]
> Re #214: could we also have something like
> 
> `target_include_directories(libwildmidi_static INTERFACE $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>)`
> 
> so that projects pulling in Wildmidi via `add_subdirectory` + `target_link_libraries` get the include path wired up auto-magically? (I could work on this)

Send a patch or issue a pull request here. Make sure the change is supported by cmake-3.1 (which is the current cmake requirement.)

**Comment by sezero** [comment]
Released 0.4.4 (and 0.3.16). Closing.
