### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by fawtytoo** [Mindwerks/wildmidi#232]
There's been no updates to the code in a long time, despite the last release date of March 2021.

**Comment by psi29a** [comment]
I and @sezero are still around, but the heart and soul of WildMIDI, @chrisisonwildcode, is no longer with us.

My original drive for WildMIDI was from another project I was working on a long time ago called thirdeye (Eye of the Beholder 3 engine reimplementation) that needed a MIDI player. I also helped get it working with Daggerfall Unity. However my motivation to keep developing WildMIDI features, like supporting more formats, has stalled. 

We're in maintenance mode at the moment. We'll do our best to handle CVE and security issues. If there is anyone who wishes to contribute, PRs are welcome.
