### ISSUE TITLE
pkg-config file is broken when CMAKE_INSTALL_{INCLUDE,LIB}DIR is absolute

### ISSUE THREAD

**Issue by alexshpilkin** [Mindwerks/wildmidi#236]
As per title: `src/wildmidi.pc.in` has

```
prefix=@CMAKE_INSTALL_PREFIX@
exec_prefix=${prefix}
libdir=${exec_prefix}/@CMAKE_INSTALL_LIBDIR@
includedir=${exec_prefix}/@CMAKE_INSTALL_INCLUDEDIR@
```

and so can’t handle absolute paths in `CMAKE_INSTALL_{INCLUDE,LIB}DIR`. This leads to a broken .pc file on NixOS in particular.

Similar to https://github.com/open-source-parsers/jsoncpp/pull/1199. See “[Concatenating paths when building pkg-config files](https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files)” for a discussion of the problem and a suggested fix (I don’t know CMake myself, sorry).

**Comment by sezero** [comment]
This should be fixed by https://github.com/Mindwerks/wildmidi/commit/c4a6330272174b80afac227f52699128afa02372: can you confirm?

If it's not fixed, or if there are further issues, please drop a note here.
