### ISSUE TITLE
AMIGAOS4: undefined reference on linking

### ISSUE THREAD

**Issue by raziel-** [Mindwerks/wildmidi#241]
`gmake amigaos4`
`Building for ppc-amigaos4`
`gmake AOS4=1`
`gmake[1]: Entering directory /Development/Porting/wildmidi-wildmidi-0.4.5/amiga`
`gcc -o wildmidi getopt_long.o wm_tty.o amiga.o wildmidi.o -L. -lWildMidi -mcrt=newlib -`
`/SDK/local/newlib/lib/libWildMidi.a(file_io.o): In function _WM_BufferFileImpl':`
`file_io.c:(.text+0xac): undefined reference to ExamineFH'`
`[1]: *** [wildmidi] Error 1`
`[1]: Leaving directory /Development/Porting/wildmidi-wildmidi-0.4.5/amiga'`
`: *** [amigaos4] Error 2`

libwildmidi.a is the one from the latest package

help?

**Comment by sezero** [comment]
Amiga code hasn't changed and it links for me, but I'm using an older sdk.
Does the following patch help?
```diff
diff --git a/src/file_io.c b/src/file_io.c
index 07ea500..1edcb21 100644
--- a/src/file_io.c
+++ b/src/file_io.c
@@ -56,6 +56,9 @@
 #elif defined(WILDMIDI_AMIGA)
 #include <proto/exec.h>
 #include <proto/dos.h>
+#ifdef __amigaos4__
+#include <dos/obsolete.h>
+#endif
 #else
 #if defined(__unix) || defined(__unix__) || defined(__APPLE__)
 #include <pwd.h>
```

**Comment by raziel-** [comment]
Unfortunately no.

Building for ppc-amigaos4
gmake AOS4=1
gmake[1]: Entering directory `/Development/Porting/wildmidi-wildmidi-0.4.5/amiga'
gcc -c -I. -I../include -Wall -W -fno-common -O2 -mcrt=newlib -DWORDS_BIGENDIAN=1 -D__USE_INLINE__ -D__USE_OLD_TIMEVAL__ -o file_io.o ../src/file_io.c
../src/file_io.c: In function 'AMIGA_filesize':
../src/file_io.c:90:13: warning: 'OBSOLETEExamineFH' is deprecated [-Wdeprecated-declarations]
   90 |             if (ExamineFH(fh, fib))
      |             ^~
In file included from /SDK/include/include_h/proto/dos.h:80,
                 from ../src/file_io.c:58:
/SDK/include/include_h/interfaces/dos.h:149:35: note: declared here
  149 |         DEPRECATED LONG APICALL (*OBSOLETEExamineFH)(struct DOSIFace *Self, BPTR fh, struct FileInfoBlock * fib);
      |                                   ^~~~~~~~~~~~~~~~~
ar cr libWildMidi.a wm_error.o file_io.o lock.o wildmidi_lib.o reverb.o gus_pat.o f_xmidi.o f_mus.o f_hmp.o f_midi.o f_hmi.o mus2mid.o xmi2mid.o internal_midi.o patches.o sample.o
ranlib libWildMidi.a
gcc -o wildmidi getopt_long.o wm_tty.o amiga.o wildmidi.o -L. -lWildMidi -mcrt=newlib -lm
/SDK/local/newlib/lib/libWildMidi.a(file_io.o): In function `_WM_BufferFileImpl':
file_io.c:(.text+0xac): undefined reference to `ExamineFH'
gmake[1]: *** [wildmidi] Error 1
gmake[1]: Leaving directory `/Development/Porting/wildmidi-wildmidi-0.4.5/amiga'
gmake: *** [amigaos4] Error 2

**Comment by raziel-** [comment]
sorry for the mess...amiga browser is...old

**Comment by sezero** [comment]
Well, I'm stumped.. It reports `'OBSOLETEExamineFH' is deprecated`
and link fails with `undefined reference to `ExamineFH'` -- notice that it
doesn't say `OBSOLETEExamineFH` ...

Everything is built cleanly yes? (make sure to do a `make distclean` )

**Comment by raziel-** [comment]
yes, clean build.

I'm not good with that stuff, but maybe it links with ExamineFH from the .a library and there it picks up ExamineFH instead of OBSOLETEExamineFH from the local file?

**Comment by sezero** [comment]
> yes, clean build.

I don't think so (see below)

> I'm not good with that stuff, but maybe it links with ExamineFH from the .a library

Where does it find that `*.a` library? Installed somewhere under system directories?
If that really is the case, remove that one and replace it with the one built with the new
patch.

**Comment by raziel-** [comment]
Right, i was mixing library files.

WITH your fix it works now, working binary compiled, thank you very much

**Comment by sezero** [comment]
OK, patch applied to git. Thank you for all the testing and feedback!

**Comment by raziel-** [comment]
@sezero

I thank YOU, sir :-)
