### ISSUE TITLE
Mindwerks homepage redirects to unrelated website

### ISSUE THREAD

**Issue by mtboehlke** [Mindwerks/wildmidi#244]
I noticed that the link to the [mindwerks homepage](http://www.mindwerks.net/projects/wildmidi) seems to redirect to an unrelated website. I just wanted to draw attention to the fact that the domain may have expired or been hijacked.

**Comment by sezero** [comment]
OK, I changed the link to point to the github project page now. (CC @psi29a: maybe you update that page and then you can change it back.)

Closing.

**Comment by sezero** [comment]
And pushed https://github.com/Mindwerks/wildmidi/commit/a128266be48f2e2fabcf308232f88c2bbaa03677 to replace the references in source tree.
