### ISSUE TITLE
Suggestion: Move Changelog in to its own file for easier parsing

### ISSUE THREAD

**Issue by luzpaz** [Mindwerks/wildmidi#246]
Would the idea of having a separate Changelog file be considered? It allows for downstream packagers to parse release changes easier.

**Comment by sezero** [comment]
> Would the idea of having a separate Changelog file be considered?

No. Wildmidi is no longer developed and is under strict maintenance mode.

**Comment by luzpaz** [comment]
> No. Wildmidi is no longer developed and is under strict maintenance mode.

Wasn't aware of that. Maybe add that to the README then (for posterity) ?
