### ISSUE TITLE
Can't play big midi files

### ISSUE THREAD

**Issue by D-u-c-k-s-e-l** [Mindwerks/wildmidi#249]
I downloaded the midi file mentioned in [this video](https://www.youtube.com/watch?v=DtUx06Vdr4k). Specifically, the `.mid` file contained in [this `.xz.xz` file](https://cdn.discordapp.com/attachments/253688726998351872/563579536198074369/BARTX.mid.xz.xz). When I tried to play it, (using `wildmidi FILENAME.mid`) I got the following error.

```
Playing BARTX.mid  Skipping: Error (_WM_BufferFileImpl:230) BARTX.mid (Refusing to load unusually long file)
Shutting down sound output
```

Is there a way to override this, and do I need more swap than a normal amount? This is a silly thing to be doing, and there's no real need to be able to play it. I'm only making this issue because there were no search results for this error message.

**Comment by D-u-c-k-s-e-l** [comment]
It looks like the error is occurring on line `230` of [`src/file_io.c`](https://github.com/Mindwerks/wildmidi/blob/master/src/file_io.c).

**Comment by sezero** [comment]
libwildmidi loads the whole midi file in memory for processing. The midi link doesn't seem to be available anymore. However, looking at the youtube link you gave, a terrabytes long midi? No, I don't think we'd ever support that (at least not with the file processing methods we currently use.)

I'm closing this as WONTFIX. @psi29a: If you have other opinions on this, feel free to re-open.

**Comment by psi29a** [comment]
Agreed.
