### ISSUE TITLE
player `-d xxx` is rejected but `--device=xxx` works

### ISSUE THREAD

**Issue by sezero** [Mindwerks/wildmidi#250]
@psi29a, @winterheart: With alsa or oss configured, `--device=default` or `--device=/dev/dsp` works, but `-d default` or `-d /dev/dsp` does not: Fails with `./wildmidi: invalid option -- 'd' `

It used to work before (e.g. in 0.4.5) -- what am I doing wrong? (It's probably something obvious, but I can't see it for now..)

(_Originally posted by @sezero in https://github.com/Mindwerks/wildmidi/issues/223#issuecomment-2028886612_)

**Comment by oreo639** [comment]
The `-d` option got removed here: https://github.com/Mindwerks/wildmidi/commit/889a83700f0f6cb432837af87ab0397f7d8464fe#diff-c3e8abef5f54490b4c232e68b2215b1077fa323fe158b1bf3a7f0a85fb9c2adbR432

**Comment by sezero** [comment]
> The `-d` option got removed here: [889a837#diff-c3e8abef5f54490b4c232e68b2215b1077fa323fe158b1bf3a7f0a85fb9c2adbR432](https://github.com/Mindwerks/wildmidi/commit/889a83700f0f6cb432837af87ab0397f7d8464fe#diff-c3e8abef5f54490b4c232e68b2215b1077fa323fe158b1bf3a7f0a85fb9c2adbR432)
> 
> (the removal of `d:` from `getopt_long()`)

But it was added back here: https://github.com/Mindwerks/wildmidi/commit/1b397db53f0c696e2b4bf060bbd765079f6cdb65

**Comment by sezero** [comment]
> > (the removal of `d:` from `getopt_long()`)

Ah that one, obviously missed that fixing now.

**Comment by sezero** [comment]
Fixed by https://github.com/Mindwerks/wildmidi/commit/22b81266d9bdb99d62a8b7fde97c3f1d8dadcd82

Thanks @oreo639
