### ISSUE TITLE
prints to stdout and stderr from the library are plain annoying

### ISSUE THREAD

**Issue by sezero** [Mindwerks/wildmidi#41]
As $TITLE says... We should invent better error reporting for the library. (0.4.x material.)

**Comment by chrisisonwildcode** [comment]
If you see any further fprintf's in -updates branch, please just comment them out as they will be artefacts from my debugging the code.

Closing this.

**Comment by sezero** [comment]
On 1/1/15, chrisisonwildcode <notifications@github.com> wrote:
> Closed #41.
>

The library still prints to console, not via direct printf() calls,
but via WM_ERROR etc which in turn call [f]printf()

So, this is not actually fixed...

**Comment by psi29a** [comment]
Re-opening until it is fixed.

**Comment by chrisisonwildcode** [comment]
have an idea for this ... will have a play later today and then get feedback on it ...

**Comment by psi29a** [comment]
@chrisisonwildcode still playing? :)

**Comment by sezero** [comment]
We actually need to invent a new api for this, such as WildMidi_LastError() or whatever...

**Comment by psi29a** [comment]
Additional functions in the API aren't a problem. Though this solution I think is best, like how OpenAL does things.

**Comment by chrisisonwildcode** [comment]
Check WildMidi_GetError branch for part 1 of the solution

**Comment by sezero** [comment]
On 3/12/15, chrisisonwildcode <notifications@github.com> wrote:
> Check WildMidi_GetError branch for part 1 of the solution
>

Seems like going to a good direction.

(BTW, the new branch is based on the File_check branch which
needs a compile fix: do you allow me to handle it?)

**Comment by chrisisonwildcode** [comment]
Sure go ahead

**Comment by sezero** [comment]
Since commit 9154dfd, we are going towards a good direction.

However I suggest that we especially remove __FILE__ usage
(which results in absolute paths being reported) and also simplify
the error messages.

**Comment by chrisisonwildcode** [comment]
I am still trying to work out what to do about a warning in the guspat code and -x converter errors.

I can remove __FILE__ references in part 2 of the error update.

As for simplified messages, what did you have in mind?

**Comment by sezero** [comment]
On 3/16/15, chrisisonwildcode <notifications@github.com> wrote:
> I am still trying to work out what to do about a warning in the guspat code
> and -x converter errors.
>

OK,

> I can remove __FILE__ references in part 2 of the error update.
>

I'd appreciate it, thanks

> As for simplified messages, what did you have in mind?
>

I mean, instead of printing a kilometer long message like
"somefile:someline: failed opening /some/path/timidity.cfg (no such
file.. etc...)"

we can simply print:
"failed opening /some/path/timidity.cfg"

... which can be enough for most purposes.

**Comment by chrisisonwildcode** [comment]
In some areas the message would be the same. If users post the messages and they are without a reference point then we would not even know where to begin to help them.

**Comment by psi29a** [comment]
@sezero is this something that can be taken care of shortly or can be delayed to 0.4.1 ?

**Comment by sezero** [comment]
> @sezero is this something that can be taken care of shortly

No

> or can be delayed to 0.4.1 ?

It can be delayed.

**Comment by psi29a** [comment]
I don't like this... but I really want 0.4 into the wild with feedback, even if it is negative feedback.

**Comment by sezero** [comment]
I worked a little on this: see the wm_error branch. Are
the changes as they are acceptable?

There are a lot 0.3.x series remnants in there, all as
a result of directly changing the old 0.3.x _WM_ERROR()
calls into _WM_GLOBAL_ERROR() :

- There are many appearances of two successives calls
to _WM_GLOBAL_ERROR(), one for reporting the strerror
result from the OS and the next for reporting that an
expected action failed (all I can see are WM_ERR_LOAD).
In 0.3.x those calls printed to stderr so both appeared
on the terminal, but now we have only one active error
string: the second _WM_GLOBAL_ERROR() is overriding the
message from the first. We must choose which to report
(my preference would be the first one.)  This is present
in wildmidi_lib.c, file_io.c, and gus_pat.c.

- There are uses of _WM_GLOBAL_ERROR() where no error is
actually returned: e.g. "(syntax error in patch line)"
message in wildmidi_lib.c:WM_LoadConfig(). Those used to
print to stderr in 0.3, but now they are not visible at
all because there is no error return. If the intention
is ony printing a warning message, I think the newly
invented _WM_DEBUG_MSG() would be more suitable because
it prints to stderr. Otherwise we'll need to invent a
method to push our warning message to user in some other
way, which seems not possible without breaking any and
everything, or, we can just remove the messages.

Comments?

**Comment by sezero** [comment]
With the wm_error branch merged, master is rather cleaned up. I also pushed 3056599 to clean it further: Please review and test.

**Comment by sezero** [comment]
With the latest changes, master branch seems cleaner. The error messages are still too long, but more tolerable. There are still some debug prints in there, if we want we can make them configurable at compile time, but I won't push it further.

**Comment by psi29a** [comment]
It is assuredly cleaner now. Thank you for that.

**Comment by sezero** [comment]
With our current state, I doubt that it will get any better. Closing.
