### ISSUE TITLE
change type of rate from 16 bit to 32 bit

### ISSUE THREAD

**Issue by sezero** [Mindwerks/wildmidi#44]
WM_SampleRate is unsigned short. Accordingly, WildMidi_Init() accepts an unsigned short rate parameter. This limits the highest possible sample rate to 65535, and if a user passes something larger, say 96000, conversion results in weird unintended values. Changing the type to unsigned int (or uint32_t) removes the limitation. I _think_ that the only change needs to be made mechanically  on WM_SampleRate and WildMidi_Init(), if there are subtleties I am not aware of them yet.

If this is acceptable, it is a v0.4-only material.

**Comment by psi29a** [comment]
@sezero & @chrisisonwildcode : how are we doing here? Shall I bump this to 0.4.1 release or wishlist?

**Comment by sezero** [comment]
On 1/2/15, Bret Curtis <notifications@github.com> wrote:
> @sezero & @chrisisonwildcode : how are we doing here? Shall I bump this to
> 0.4.1 release or wishlist?

It depends on Chris' willingness to implement this.
I am OK with the current status.

**Comment by chrisisonwildcode** [comment]
I'd wishlist this for now. 

Here is the issue with trying to implement more that 16bit rate as it stands ... all the old sample pack that people are likely to use are all 16bit anyway. So pushing to a 32bit rate is not going to improve quality any.

Yes later on we can look at this when the need arrises (and it is bound to as we add sample formats at a later stage), but we need to be prepared for some headaches.

**Comment by sezero** [comment]
This looks like a `WONTFIX` anymore
