### ISSUE TITLE
OpenBSD can't load library

### ISSUE THREAD

**Issue by psi29a** [Mindwerks/wildmidi#56]
Normally, when you build the libs and the player, the player will then look first in the local directory for it's necessary library and if it can't be found it will then look in the standard lib location.

On OpenBSD, if I run ./wildmidi I get:

<pre>
$ ./wildmidi
./wildmidi: can't load library '../libWildMidi.so'
</pre>

If I create a directory, put wildmidi in there then try to run it, it then finds the '../libWildMidi.sl' and works.

Something is very odd with how wildmidi is being build/linked on OpenBSD.

**Comment by chrisisonwildcode** [comment]
should we look at fixing this for 0.4.0 since it is a platform wildmidi should be working on?

**Comment by psi29a** [comment]
it does work on openbsd, but you have explicitly tell the damn thing where the lib is in relation to the binary. it doesn't have a PATH variable to iterate through like on linux or osx.

**Comment by psi29a** [comment]
I'll give this another go eventually. I was hoping that someone that actually uses OpenBSD would eventually sent patches. ;)

**Comment by psi29a** [comment]
Should be solved with this commit: https://github.com/Mindwerks/wildmidi/pull/154/commits/93697ece759acc02415e73ef3233a21c1c271ffe

**Comment by sezero** [comment]
Closing .
