### ISSUE TITLE
ADL support

### ISSUE THREAD

**Issue by psi29a** [Mindwerks/wildmidi#67]
Westwood Studios created this format for storing AdLib music for many of their games.

Technical information:
http://www.vgmpf.com/Wiki/index.php?title=ADL

Comment: A GPLv2 c++ plugin for winamp (last touched, 2010) exists here:
http://adplug.sourceforge.net/
We could use some of this code to help. It also happens to support the following formats:
A2M: AdLib Tracker 2 by subz3ro
ADL: Westwood ADL File Format
AMD: AMUSIC Adlib Tracker by Elyssis
BAM: Bob's Adlib Music Format
CFF: BoomTracker 4.0 by CUD
CMF: Creative Music File Format by Creative Technology
D00: EdLib by Vibrants
DFM: Digital-FM by R.Verhaag
DMO: Twin TrackPlayer by TwinTeam
DRO: DOSBox Raw OPL Format
DTM: DeFy Adlib Tracker by DeFy
HSC: HSC Adlib Composer by Hannes Seifert, HSC-Tracker by Electronic Rats
HSP: HSC Packed by Number Six / Aegis Corp.
IMF: Apogee IMF File Format
KSM: Ken Silverman's Music Format
LAA: LucasArts AdLib Audio File Format by LucasArts
LDS: LOUDNESS Sound System
M: Origin AdLib Music Format
MAD: Mlat Adlib Tracker
MID: MIDI Audio File Format
MKJ: MKJamz by M \ K Productions (preliminary)
MSC: AdLib MSCplay
MTK: MPU-401 Trakker by SuBZeR0
RAD: Reality ADlib Tracker by Reality
RAW: RdosPlay RAW file format by RDOS
RIX: Softstar RIX OPL Music Format
ROL: AdLib Visual Composer by AdLib Inc.
S3M: Screamtracker 3 by Future Crew
SA2: Surprise! Adlib Tracker 2 by Surprise! Productions
SAT: Surprise! Adlib Tracker by Surprise! Productions
SCI: Sierra's AdLib Audio File Format
SNG: SNGPlay by BUGSY of OBSESSION
SNG: Faust Music Creator by FAUST
SNG: Adlib Tracker 1.0 by TJ
XAD: eXotic ADlib Format by Riven the Mage
XMS: XMS-Tracker by MaDoKaN/E.S.G
XSM: eXtra Simple Music by Davey W Taylor

**Comment by psi29a** [comment]
Update, it turns out that AdPlug is LGPL, just like WildMIDI library. It has its own player like WildMIDI does.

Now the question is, since this exists... do we really need to support OPL based music in WildMIDI when it is already done elsewhere?

We support files they don't, and they support files we don't. So not much in the way overlap.

What do you guys think?

**Comment by sezero** [comment]
I feel against bloating a library, but that's just me.  At least we should polish what we have first.

**Comment by psi29a** [comment]
I agree as well. Keep our support for MIDI likes only.

**Comment by stuartpb** [comment]
Except that this project is maintained, and AdPlug isn't; I'd like to see the abandoned AdPlug's supported file formats be subsumed to live on in a living project.

**Comment by psi29a** [comment]
Latest commit d7cb4d8  13 days ago

https://github.com/adplug/adplug/commits/master

Seems pretty active to me...

**Comment by stuartpb** [comment]
Oh, I was looking at

> A GPLv2 c++ plugin for winamp (last touched, 2010) exists here: http://adplug.sourceforge.net/

If AdPlug is being maintained and has a clearly different focus, then sure, keep 'em separate.

**Comment by chrisisonwildcode** [comment]
I agree, keep our focus on midi like formats.
