### ISSUE TITLE
HMP and HMI support

### ISSUE THREAD

**Issue by psi29a** [Mindwerks/wildmidi#75]
There are 3 versions that need to be supported, but thankfully there are many examples and specifications.

<quote>
Human Machine Interface (HMI) is a MIDI-like format named after the company that created it, Human Machine Interfaces. The format is derived from the earlier HMP format. The format was used by the Sound Operating System middleware library for audio playback, a competitor of the XMI used in the Miles Sound System.

Human Machine Interfaces MIDI P (HMP) is a MIDI-like HMI created by Human Machine Interfaces. The format seems to lack tracking tags, so the format may be something akin to a MIDI 0 file.
The extension is generally .hmp. Descent used the extension .hmq for song variants destined to be played on FM synthesis sound cards.

Technical

There are two existing versions of the HMP format. All HMP files begin with "HMIMIDIP". The oldest version has its signature followed by a null byte; while the revised version, dated from January 31, 1995, has the signature followed by this date (HMIMIDIP013195). A second revision, dated from June 15, 1995, resulted in the HMI format.
</quote>

This covers music from:
1994-05-06	Magic Carpet (DOS)
1994-??-??	Sensible Golf (DOS)
1995-03-17	Descent (DOS)
1995-08-??	Abuse (DOS)
1995-??-??	The Terminator: Future Shock (DOS)
1996-03-13	Descent II (DOS)
1996-03-13	Descent II (DOS)
1996-08-31	Daggerfall (DOS)
1996-??-??	The Terminator: SkyNET (DOS)
1997-06-30	Carmageddon (DOS)
1997-07-15	X-COM Apocalypse (DOS)

**Comment by chrisisonwildcode** [comment]
ok, I've taken a look at the 2 of the files that were in the dropbox ... the data they contain is not valid for the format they state as is (taking into account the 5 leading bytes). To verify it wasn't some sort of variation of the hmp file format I looked for MIDI style data which is easily read with a hex editor. Unfortunately the data does not even make sense from a MIDI context. I'm betting these files are compressed/encrypted/modified from hmp files.

**Comment by psi29a** [comment]
How are doing on HMI/HMP support? We good here?  Documentation is fixed up?  If so, please close this sucker! :)

**Comment by chrisisonwildcode** [comment]
I'll check docs later today and close once done

**Comment by chrisisonwildcode** [comment]
Looks all good, will close this one up.

**Comment by psi29a** [comment]
Great!

**Comment by PolarisBeaver** [comment]
I am unable to play HMI files I manually extracted from the RESOURCE file for the game 3D Ultra Pinball by Sierra.

I think I extracted the data at the correct offsets. I started extracting the songs with the very first bytes in the file being "HMI-MIDISONG061595", and as for the ending of each song file, I wasn't so sure of where the file is supposed to end. In the attachment, you can see the 2 different file cutoffs I tried, one will end just before the next instance of "HMI-MIDISONG061595", and the other song was extracted from the very end of the RESOURCE file (so it will have a slightly different file end). Neither play in this program, but I was able to play them in Foobar2000 using a midi plugin. Is this program having trouble, or did I extract the data wrong? HMIs in question are included.

[HMI songs.zip](https://github.com/Mindwerks/wildmidi/files/752615/HMI.songs.zip)

**Comment by psi29a** [comment]
```
bcurtis@WhiteQueen:~/Workspace/Private/Wildmidi/build$ ./wildmidi-devtest  ~/Downloads/HMI.songs/song.hmi 
DevTest for WildMIDI 0.4 - For testing purposes only

Testing: /home/bcurtis/Downloads/HMI.songs/song.hmi
116 notes still on after end of file
Success
```
Seems to say it is valid but has a lot of notes still on in the end.

I just played it back with wildmidi without a problem. They play fine to me, it is about 41s long.

```
Playing song.hmi 
[Approx  0m 41s Total]
                              [    ] [100] [ 0m 41s Processed] [100%] /  
Shutting down sound output
```
Here is the rendering to mp3:
https://dl.dropboxusercontent.com/u/396161/song.mp3

I think perhaps the problem lies on your side? Can you play back any other midi's?

**Comment by chrisisonwildcode** [comment]
I'll have a look tonight, it'll be a nice change from the norm.

**Comment by psi29a** [comment]
> Actually, I just popped it into the hex-editor and found out that each of the hmp files you sent have a 5 byte buffer in the front. That explains why we couldn't read the record, I bet if you trim those bits, it should play just fine.
> 
> Some of the buffer bytes are: AB 97 00 00 0F 23 14 01 00 0F 90 AA 00 00 0F
> 
> Looks like 00 0F is the end marker for whatever came before "HMIMIDIP013195". Are you sure the files were ripped right?

Doing some research here, these files were compressed. So inflating ingame1.hmp went from 5K to 38K; I used a tool found here to do so: https://github.com/FatalDecomp/Whiptools

Not sure if we want to support that. 

Here is a script if you're interested
[unmangle.py](https://github.com/user-attachments/files/29889152/unmangle.py)

**Comment by MoffD** [comment]
Oh wow, thanks for the update! I realized much later they were probably
compressed, sorry for the confusion. Also thanks for the link to that
decompilation/decompression tool

**Comment by psi29a** [comment]
> Oh wow, thanks for the update! I realized much later they were probably
> compressed, sorry for the confusion. Also thanks for the link to that
> decompilation/decompression tool
> […](#)

Cheers m8, I decided to add native support in wildmidi, it's part of the PR that should resolve the issue :)
