### ISSUE TITLE
Cross platform testing

### ISSUE THREAD

**Issue by chrisisonwildcode** [Mindwerks/wildmidi#81]
Sorry to open this here but with only 2 options for discussions, and no-one but me keeping the IRC channel warm atm, this was the better option.

I know some of you have access to cross platform testing, just letting you guys know I have Oracle VM Virtual Box with Win7 (my copy), Ubuntu 14.07, FreeBSD 10, and Solaris 11.1 installed on an OSX host for testing later on.

**Comment by psi29a** [comment]
We'll get the CIs doing compile testing on linux/osx/windows... which is about 90% of the use-cases. 

I think between the three of us, we do OK withauditory testing.

**Comment by chrisisonwildcode** [comment]
I also have freebsd and solaris to add to the mix if needed

**Comment by psi29a** [comment]
I have those as well in my QEMU, but honestly... I don't use them until someone files a bug specific to that platform. ;)  Close this for now?

**Comment by kotc** [comment]
throw cygwin in the mix? im using libwildmidi with my player app and it works great (tested 0.4.0 in cygwin and native linux (slackware)). btw. what is the irc channel/server name?

**Comment by psi29a** [comment]
#wildmidi @ irc.freenode.org

**Comment by psi29a** [comment]
Working on this now for CI.

Debian does this for us.

**Comment by psi29a** [comment]
2 our of 3 major OSes now under CI control:
https://travis-ci.org/Mindwerks/wildmidi/builds/149464666

I have the files in place for appveyor, just need to turn it on and see what breaks. :)

Windows is online, I'm going to close this thread. Individual platform support will be done by those willing to make patches and PRs.

**Comment by psi29a** [comment]
OK, we now have all 3 major platforms under CI so we'll have coverage for every commit.

We can add unit-testing later that will help make sure that inputs/outputs are as expected. This is in another issue being tracked.

As for other platforms, if people want to support them they are free to send a patch/PR.
