### ISSUE TITLE
decay_samples issues

### ISSUE THREAD

**Issue by chrisisonwildcode** [Mindwerks/wildmidi#84]
ok, if I wrote the code for decay samples then I must of been on something, but it definitely does not look my doing thought.

First issue with it is that it does not take into account running events.

Second issue is that when calling for drum instruments it is using the wrong data offset.

Third issue is that at the point of the code that it is at, everything would be set to piano because the setup code does not set patch information, the playback code does. Setup code just sets up the array of function calls that playback uses it does not actually do any processing of events ...

**Comment by psi29a** [comment]
@chrisisonwildcode Is this something for 0.4 or 0.4.1?

**Comment by chrisisonwildcode** [comment]
This could probably be closed ... decay_samples code was replaced.

**Comment by psi29a** [comment]
Done!
