### ISSUE TITLE
Audio output is incorrect

### ISSUE THREAD

**Issue by chrisisonwildcode** [Mindwerks/wildmidi#91]
Both wav file output and audio driver output is incorrect. This means there is an issue with either WildMidi_GetOutput, or in the player. I managed to rule out the parsing of the files due to midi output not showing any evidence of causing the issue I am hearing in the audio.

The issues I am hearing are 

 - an echo of audio, even when reverb engine is off (yet to verify this in the code path in case someone changed or added its usage elsewhere). This is not caused by the WM_ParseNew functions as the midi file output has ruled them out.

 - Note release taking way too long. This could be an audio effect of the echo issue however I am noting it for completeness. This also is not caused by the WM_ParseNew functions as the midi file output has ruled them out.

**Comment by chrisisonwildcode** [comment]
Going to close this since original issue seems to be resolved

**Comment by psi29a** [comment]
@sezero can you validate this?
