### ISSUE TITLE
Switch to Curved Volumes by Default?

### ISSUE THREAD

**Issue by chrisisonwildcode** [Mindwerks/wildmidi#94]
Looking briefly at the midi specs I managed to get my hands on it looks like by default MIDI wants curved volume levels, with slightly different curves for panning. As I verify that we are doing things correctly (in some cases we're not) I want to get your opinion on switching to curved volume/pan/expression/MasterVolume levels by default.

**Comment by chrisisonwildcode** [comment]
closing this, its pretty much a personal preference.

**Comment by psi29a** [comment]
Re-opened... and moved to wishlist. :)

**Comment by sezero** [comment]
Looks like a `WONTFIX` anymore.
