### ISSUE TITLE
provide proper thread-safety to the library

### ISSUE THREAD

**Issue by sezero** [Mindwerks/wildmidi#99]
The existing WM_Lock()/WM_Unlock() functionality is rather flaky.
We can change things to use OS-specific mutexes, i.e. pthread on
unices including darwin, mutex handles on windows, etc.

See libmikmod (mikmod.sf.net) for an example.

**Comment by sezero** [comment]
> If only we could break the API to make a better library. ;)

We already broke the api in 0.4.0...

**Comment by psi29a** [comment]
derp, we didn't break the api... old applications can still link against libwildmidi right?

We've added to the API.

**Comment by sezero** [comment]
On 2/16/15, Bret Curtis <notifications@github.com> wrote:
> derp, we didn't break the api... old applications can still link against
> libwildmidi right?

We did break it. See the README for 0.4 differences. IIRC, most,
if not all, of them are due to stdint types changes. And we also
changed abi compatibility by returning host-endian audio data
instead of little-endian.

**Comment by psi29a** [comment]
That's right, we did do that. Thanks for reminding  me. I know that @chrisisonwildcode wanted us not to do that so that SiS and others wouldn't cry... but I think at this point, this is a major revision and breaking stuff.

I've always been anti-globals, if they are gone, then there isn't a need for locking. The state exists in the opaque pointer that you get back from wildmidi_init and when you call other functions, you pass the pointer as well.

This however will really break applications. :)

**Comment by sezero** [comment]
Globals are the major offender here, yes.  However, an app can access the same context, even the same midi from two different threads and in that case you'll need the thread safety there too.  I know this is maybe stretching it too far, but it's not an impossible scenario, with or without the global state eliminated.

**Comment by chrisisonwildcode** [comment]
Yeah, you guys changed the API so there is no backwards compatibility for older apps.  Locks are still needed for the reason sezero stated. 

The only globals should now be the audio rate, the sample data and the global options with everything else handled through the mdi struct.

**Comment by sezero** [comment]
On 2/16/15, chrisisonwildcode <notifications@github.com> wrote:
> Yeah, you guys changed the API so there is no backwards compatibility for older apps.

Off-topic:  We can still go back to 0.2/0.3-compatible api if
required. Not a very big job,

**Comment by psi29a** [comment]
Do we want to go back, or do we want to go forward? Is this a topic for another issue?

How much effort would it take to fix the issue in this thread? Use proper mutexes?

**Comment by sezero** [comment]
On 2/16/15, Bret Curtis <notifications@github.com> wrote:
> Do we want to go back, or do we want to go forward?

Up to you guys

> Is this a topic for another issue?

Yes

> How much effort would it take to fix the issue in this thread? Use proper
> mutexes?

I say yes. mikmod does the same for _quite_ some time and it works.
The only thing is that locks will need OS-specific coding. Unix and osx
can live with pthreads, windows and others need their own stuff, etc.

**Comment by psi29a** [comment]
I see it needs to be done then.

**Comment by sezero** [comment]
> I see, it needs to be done then.

I'll start in a new threads branch soon, then.

**Comment by psi29a** [comment]
How soon is soon? ;)

**Comment by psi29a** [comment]
Hah!  I had a solution for this using contexts (remove need for globals)... but someone was afraid of api breakage.

**Comment by sezero** [comment]
On 8/1/16, Bret Curtis <notifications@github.com> wrote:
> Hah!  I had a solution for this using contexts (remove need for globals)...
> but someone was afraid of api breakage.
>

We already broke api once, and the users of 0.4 aren't even properly
adapting to the new api (no adjustment for endianism, maybe they are
only targeting little endian.)

We _can_ do this, though, with another api breakage, but Chris would
strangle us in our sleep..

**Comment by sezero** [comment]
This looks like a `WONTFIX` anymore.
